<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190722143415 extends AbstractMigration
{
  public function getDescription(): string
  {
    return '';
  }

  public function up(Schema $schema): void
  {
    // this up() migration is auto-generated, please modify it to your needs
    $this->abortIf('mysql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

    $this->addSql('ALTER TABLE project DROP IF EXISTS fb_post_id, DROP IF EXISTS fb_post_url, CHANGE approved_by_user approved_by_user INT DEFAULT NULL, CHANGE category_id category_id INT DEFAULT NULL, CHANGE gamejam_id gamejam_id INT DEFAULT NULL, CHANGE directory_hash directory_hash VARCHAR(255) DEFAULT NULL, CHANGE catrobat_version_name catrobat_version_name VARCHAR(255) DEFAULT \'\' NOT NULL, CHANGE upload_ip upload_ip VARCHAR(255) DEFAULT \'\' NOT NULL, CHANGE flavor flavor VARCHAR(255) DEFAULT \'pocketcode\' NOT NULL, CHANGE upload_language upload_language VARCHAR(255) DEFAULT \'\' NOT NULL, CHANGE apk_request_time apk_request_time DATETIME DEFAULT NULL, CHANGE gamejam_submission_date gamejam_submission_date DATETIME DEFAULT NULL, CHANGE remix_migrated_at remix_migrated_at DATETIME DEFAULT NULL');
    $this->addSql('ALTER TABLE fos_user DROP IF EXISTS facebook_access_token, CHANGE salt salt VARCHAR(255) DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE date_of_birth date_of_birth DATETIME DEFAULT NULL, CHANGE firstname firstname VARCHAR(64) DEFAULT NULL, CHANGE lastname lastname VARCHAR(64) DEFAULT NULL, CHANGE website website VARCHAR(64) DEFAULT NULL, CHANGE biography biography VARCHAR(1000) DEFAULT NULL, CHANGE gender gender VARCHAR(1) DEFAULT NULL, CHANGE locale locale VARCHAR(8) DEFAULT NULL, CHANGE timezone timezone VARCHAR(64) DEFAULT NULL, CHANGE phone phone VARCHAR(64) DEFAULT NULL, CHANGE facebook_uid facebook_uid VARCHAR(255) DEFAULT NULL, CHANGE facebook_name facebook_name VARCHAR(255) DEFAULT NULL, CHANGE facebook_data facebook_data JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE twitter_uid twitter_uid VARCHAR(255) DEFAULT NULL, CHANGE twitter_name twitter_name VARCHAR(255) DEFAULT NULL, CHANGE twitter_data twitter_data JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE gplus_uid gplus_uid VARCHAR(255) DEFAULT NULL, CHANGE gplus_name gplus_name VARCHAR(255) DEFAULT NULL, CHANGE gplus_data gplus_data JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE token token VARCHAR(255) DEFAULT NULL, CHANGE two_step_code two_step_code VARCHAR(255) DEFAULT NULL, CHANGE upload_token upload_token VARCHAR(300) DEFAULT NULL, CHANGE country country VARCHAR(5) DEFAULT \'\' NOT NULL, CHANGE additional_email additional_email VARCHAR(255) DEFAULT NULL, CHANGE gplus_access_token gplus_access_token VARCHAR(300) DEFAULT NULL, CHANGE gplus_id_token gplus_id_token VARCHAR(5000) DEFAULT NULL, CHANGE gplus_refresh_token gplus_refresh_token VARCHAR(300) DEFAULT NULL, CHANGE dn dn VARCHAR(255) DEFAULT NULL');
    $this->addSql('ALTER TABLE tags CHANGE en en VARCHAR(255) DEFAULT NULL, CHANGE de de VARCHAR(255) DEFAULT NULL, CHANGE it it VARCHAR(255) DEFAULT NULL, CHANGE fr fr VARCHAR(255) DEFAULT NULL');
    $this->addSql('ALTER TABLE extension CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE prefix prefix VARCHAR(255) DEFAULT NULL');
    $this->addSql('ALTER TABLE project_remix_relation CHANGE seen_at seen_at DATETIME DEFAULT NULL');
    $this->addSql('ALTER TABLE project_remix_backward_relation CHANGE seen_at seen_at DATETIME DEFAULT NULL');
    $this->addSql('ALTER TABLE GameJam CHANGE form_url form_url VARCHAR(300) DEFAULT NULL, CHANGE hashtag hashtag VARCHAR(100) DEFAULT NULL, CHANGE flavor flavor VARCHAR(100) DEFAULT NULL');
    $this->addSql('ALTER TABLE project_downloads CHANGE user_id user_id INT DEFAULT NULL, CHANGE rec_from_project_id rec_from_project_id INT DEFAULT NULL, CHANGE recommended_by_project_id recommended_by_project_id INT DEFAULT NULL, CHANGE user_agent user_agent VARCHAR(255) DEFAULT \'\', CHANGE referrer referrer VARCHAR(255) DEFAULT \'\', CHANGE recommended_by_page_id recommended_by_page_id INT DEFAULT NULL, CHANGE locale locale VARCHAR(255) DEFAULT NULL');
    $this->addSql('ALTER TABLE scratch_project CHANGE name name VARCHAR(300) DEFAULT NULL');
    $this->addSql('ALTER TABLE click_statistics CHANGE tag_id tag_id INT DEFAULT NULL, CHANGE extension_id extension_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE rec_from_project_id rec_from_project_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE user_agent user_agent VARCHAR(255) DEFAULT \'\', CHANGE referrer referrer VARCHAR(255) DEFAULT \'\', CHANGE scratch_project_id scratch_project_id INT DEFAULT NULL, CHANGE locale locale VARCHAR(255) DEFAULT NULL');
    $this->addSql('ALTER TABLE user_comment CHANGE projects projects INT DEFAULT NULL');
    $this->addSql('ALTER TABLE CatroNotification CHANGE comment_id comment_id INT DEFAULT NULL, CHANGE like_from like_from INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE follower_id follower_id INT DEFAULT NULL');
    $this->addSql('ALTER TABLE featured CHANGE project_id project_id INT DEFAULT NULL, CHANGE url url VARCHAR(255) DEFAULT NULL, CHANGE flavor flavor VARCHAR(255) DEFAULT \'pocketcode\' NOT NULL');
    $this->addSql('ALTER TABLE homepage_click_statistics CHANGE project_id project_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE locale locale VARCHAR(255) DEFAULT NULL, CHANGE user_agent user_agent VARCHAR(255) DEFAULT \'\', CHANGE referrer referrer VARCHAR(255) DEFAULT \'\'');
    $this->addSql('ALTER TABLE media_package_file CHANGE category_id category_id INT DEFAULT NULL, CHANGE flavor flavor VARCHAR(255) DEFAULT \'pocketcode\', CHANGE author author VARCHAR(255) DEFAULT NULL');
    $this->addSql('ALTER TABLE ProjectInappropriateReport CHANGE user_id user_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL');
    $this->addSql('ALTER TABLE acl_object_identities CHANGE parent_object_identity_id parent_object_identity_id INT UNSIGNED DEFAULT NULL');
    $this->addSql('ALTER TABLE acl_entries CHANGE object_identity_id object_identity_id INT UNSIGNED DEFAULT NULL, CHANGE field_name field_name VARCHAR(50) DEFAULT NULL');
  }

  public function down(Schema $schema): void
  {
    // this down() migration is auto-generated, please modify it to your needs
    $this->abortIf('mysql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

    $this->addSql('ALTER TABLE CatroNotification CHANGE comment_id comment_id INT DEFAULT NULL, CHANGE like_from like_from INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE follower_id follower_id INT DEFAULT NULL');
    $this->addSql('ALTER TABLE GameJam CHANGE form_url form_url VARCHAR(300) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE hashtag hashtag VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE flavor flavor VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE ProjectInappropriateReport CHANGE user_id user_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL');
    $this->addSql('ALTER TABLE acl_entries CHANGE object_identity_id object_identity_id INT UNSIGNED DEFAULT NULL, CHANGE field_name field_name VARCHAR(50) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
    $this->addSql('ALTER TABLE acl_object_identities CHANGE parent_object_identity_id parent_object_identity_id INT UNSIGNED DEFAULT NULL');
    $this->addSql('ALTER TABLE click_statistics CHANGE tag_id tag_id INT DEFAULT NULL, CHANGE extension_id extension_id INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE rec_from_project_id rec_from_project_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE scratch_project_id scratch_project_id INT DEFAULT NULL, CHANGE locale locale VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE user_agent user_agent VARCHAR(255) DEFAULT \'\'\'\' COLLATE utf8mb4_unicode_ci, CHANGE referrer referrer VARCHAR(255) DEFAULT \'\'\'\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE extension CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE prefix prefix VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE featured CHANGE project_id project_id INT DEFAULT NULL, CHANGE url url VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE flavor flavor VARCHAR(255) DEFAULT \'\'pocketcode\'\' NOT NULL COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE fos_user ADD facebook_access_token VARCHAR(300) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE salt salt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE last_login last_login DATETIME DEFAULT \'NULL\', CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE date_of_birth date_of_birth DATETIME DEFAULT \'NULL\', CHANGE firstname firstname VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE lastname lastname VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE website website VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE biography biography VARCHAR(1000) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE gender gender VARCHAR(1) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE locale locale VARCHAR(8) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE timezone timezone VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE phone phone VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE facebook_uid facebook_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE facebook_name facebook_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE facebook_data facebook_data JSON DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE twitter_uid twitter_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE twitter_name twitter_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE twitter_data twitter_data JSON DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE gplus_uid gplus_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE gplus_name gplus_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE gplus_data gplus_data JSON DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE token token VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE two_step_code two_step_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE upload_token upload_token VARCHAR(300) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE country country VARCHAR(5) DEFAULT \'\'\'\' NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE additional_email additional_email VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE dn dn VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE gplus_access_token gplus_access_token VARCHAR(300) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE gplus_id_token gplus_id_token VARCHAR(5000) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE gplus_refresh_token gplus_refresh_token VARCHAR(300) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE homepage_click_statistics CHANGE project_id project_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE locale locale VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE user_agent user_agent VARCHAR(255) DEFAULT \'\'\'\' COLLATE utf8mb4_unicode_ci, CHANGE referrer referrer VARCHAR(255) DEFAULT \'\'\'\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE media_package_file CHANGE category_id category_id INT DEFAULT NULL, CHANGE flavor flavor VARCHAR(255) DEFAULT \'\'pocketcode\'\' COLLATE utf8mb4_unicode_ci, CHANGE author author VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE project ADD fb_post_id VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, ADD fb_post_url VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE approved_by_user approved_by_user INT DEFAULT NULL, CHANGE category_id category_id INT DEFAULT NULL, CHANGE gamejam_id gamejam_id INT DEFAULT NULL, CHANGE directory_hash directory_hash VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE catrobat_version_name catrobat_version_name VARCHAR(255) DEFAULT \'\'\'\' NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE upload_ip upload_ip VARCHAR(255) DEFAULT \'\'\'\' NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE flavor flavor VARCHAR(255) DEFAULT \'\'pocketcode\'\' NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE upload_language upload_language VARCHAR(255) DEFAULT \'\'\'\' NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE remix_migrated_at remix_migrated_at DATETIME DEFAULT \'NULL\', CHANGE apk_request_time apk_request_time DATETIME DEFAULT \'NULL\', CHANGE gamejam_submission_date gamejam_submission_date DATETIME DEFAULT \'NULL\'');
    $this->addSql('ALTER TABLE project_downloads CHANGE recommended_by_project_id recommended_by_project_id INT DEFAULT NULL, CHANGE rec_from_project_id rec_from_project_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE recommended_by_page_id recommended_by_page_id INT DEFAULT NULL, CHANGE locale locale VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE user_agent user_agent VARCHAR(255) DEFAULT \'\'\'\' COLLATE utf8mb4_unicode_ci, CHANGE referrer referrer VARCHAR(255) DEFAULT \'\'\'\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE project_remix_backward_relation CHANGE seen_at seen_at DATETIME DEFAULT \'NULL\'');
    $this->addSql('ALTER TABLE project_remix_relation CHANGE seen_at seen_at DATETIME DEFAULT \'NULL\'');
    $this->addSql('ALTER TABLE scratch_project CHANGE name name VARCHAR(300) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE tags CHANGE en en VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE de de VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE it it VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE fr fr VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
    $this->addSql('ALTER TABLE user_comment CHANGE projects projects INT DEFAULT NULL');
  }
}
