#
# **Codecov** (https://codecov.io/):
#
#   - automatically merges code coverage reports (parallel running tests)
#   - code coverage reports are uploaded during the GitHub Actions
#   - posts a comment with the report to every pull request
#   - is integrated on GitHub as an APP and can be deactivated in the GitHub settings (ask a product-owner)
#   - Integrated CI checks for a minimum code quality
#   - strive for a code coverage between 80-90 percent
#   - code coverage give an indication how much has been tested - not how well!
#
#   - use this file to further configure codecov:
#

#
# In the moment coverage is only informational and should not provide CI checks to fail the pipeline
# By turning them on, minimum code coverage values can be required for a pull request to pass the CI checks.
# It is possible to either check the absolute or relative code coverage values.
# Relative metrics only inspect changes files.
#
coverage:
  status:
    project: off
    patch: off

#
# do not comment until to a pull requests after at least X builds have been uploaded from the CI pipeline
# Important keep up to date with behat + phpunit test suites and more importantly
# this number must never be smaller than the number of GitHub Actions jobs that are uploading a file
# else the report will never be commented to the pull request.
# However, if keeping this file up-to-date seems to be not feasible, this check can be completely removed,
# it is only QOL change and not required
#
comment:
    after_n_builds: 29
