fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\DB\Entity\User\User

  group:
    group_class:   App\DB\Entity\User\Group
    group_manager: sonata.user.orm.group_manager

  service:
    user_manager: App\User\UserManager
    mailer: 'fos_user.mailer.noop'
  from_email:
    address: NOT USED
    sender_name: NOT USED
