fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User

  group:
    group_class:   App\Entity\Group
    group_manager: sonata.user.orm.group_manager

  service:
    user_manager: App\Manager\UserManager
    mailer: fos_user.mailer.twig_swift # allows usage of twig templates

  # Can be removed once fos user bundle was removed
  from_email:
    address: no-reply@catrob.at
    sender_name: "No Reply"
