imports:
  - { resource: parameters.yml }

parameters:
  ldap_role_mappings:
    ROLE_MEDIAPACKAGE:  "Webserver-MediaPackageMaintainers"
    ROLE_FEATURED:      "Webserver-FeaturedProgramsMaintainers"
    ROLE_APPROVE:       "Webserver-AppApprovers"
    ROLE_SUPER_ADMIN:   "Webserver-Administrators"
    ROLE_GAMEJAM_ADMIN: "Webserver-GameJam-Administrators"


# # working testserver
#fr3d_ldap:
#    driver:
#        host: ldap.forumsys.com
#    user:
#        baseDn: dc=example, dc=com
#        attributes:
#        - { ldap_attr: uid,  user_method: setUsername }
#        - { ldap_attr: mail,  user_method: setEmail }
#        filter: (&(ObjectClass=person))


fr3d_ldap:
  driver:
    host:                '%ldap_host%'
    port:                '%ldap_port%'   # Optional
    username:            '%ldap_user%'    # Optional
    password:            '%ldap_password%'    # Optional
    bindRequiresDn:      true   # Optional
    baseDn:              '%ldap_base_dn%'   # Optional
    accountFilterFormat: (cn=%s) # Optional. sprintf format %s will be the username
    #       optReferrals:        false  # Optional
    useSsl:              true   # Enable SSL negotiation. Optional
  #       useStartTls:         true   # Enable TLS negotiation. Optional
  #       accountCanonicalForm: 3 # ACCTNAME_FORM_BACKSLASH this is only needed if your users have to login with something like HOST\User
  #       accountDomainName: HOST
  #       accountDomainNameShort: HOST # if you use the Backslash form set both to Hostname than the Username will be converted to HOST\User

  user:
    baseDn: '%ldap_base_dn%'
    filter: (&(ObjectClass=person)(cn=%s))
    attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
      - { ldap_attr: cn,  user_method: setUsername } # Default
      - { ldap_attr: mail,  user_method: setEmail } # Default

  service:
    user_hydrator: App\Catrobat\Ldap\UserHydrator      # Overrides default user hydrator
    ldap_manager: App\Entity\UserLDAPManager   # Overrides default ldap manager
#       ldap_driver: fr3d_ldap.ldap_driver.zend        # Overrides default ldap driver