parameters:
  flavors:
    - 'pocketcode'
    - 'pocketalice'
    - 'pocketgalaxy'
    - 'phirocode'
    - 'luna'
    - 'create@school'
    - 'embroidery'
    - 'arduino'
    - 'mindstorms'

  defaultFlavor: 'pocketcode'

  umbrellaTheme: 'app'
  adminTheme: 'admin'

  # All flavors + umbrellaTheme
  themeRoutes: 'app|pocketcode|pocketalice|pocketgalaxy|phirocode|luna|create\@school|embroidery|arduino|mindstorms'
