# Eslint javascript coding standard config:

env:
  browser: true
  es6: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
rules: { 'no-new': 0, 'comma-dangle': 0, 'space-before-function-paren': 0, 'indent': 0 }
