<?php

namespace Catrobat\CatrowebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
  public function findByOrderedByDownloads($limit = null, $offset = null)
  {
    return $this->findBy(array(),array('downloads' => 'desc'), $limit, $offset);
  }

  public function findByOrderedByViews($limit = null, $offset = null)
  {
    return $this->findBy(array(),array('views' => 'desc'), $limit, $offset);
  }
  
  public function findByOrderedByDate($limit = null, $offset = null)
  {
    return $this->findBy(array(),array('uploaded_at' => 'desc'), $limit, $offset);
  }
  
}
