name: 'Install node and npm modules'
description: 'Install node and npm modules. Caching is enabled for enhanced performance.'
runs:
  using: 'composite'
  steps:
    - name: 'Download and set up node (caching is enabled)'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: 'Use caching action to improve performance'
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 'Only install modules if there is no cache hit'
      # "If" not yet supported: https://github.com/actions/runner/issues/834 -> shell workaround
      #    - if: steps.npm-cache.outputs.cache-hit != 'true'
      #      run: npm ci
      shell: bash
      run: |
        if echo ${{ steps.npm-cache.outputs.cache-hit }} | grep -c "true"
        then
          echo "Cache hit - skipping dependency installation"
        else
          npm ci
        fi
