<?php

namespace App\Api\Services\Base;

use Exception;
use Symfony\Contracts\Translation\TranslatorInterface;

trait TranslatorAwareTrait
{
  private TranslatorInterface $translator;

  private ?string $used_locale = null;

  public function initTranslator(TranslatorInterface $translator): void
  {
    $this->translator = $translator;
  }

  public function __(string $id, array $parameter = [], ?string $locale = null): string
  {
    return $this->trans($id, $parameter, $locale);
  }

  public function trans(string $id, array $parameter = [], ?string $locale = null): string
  {
    $domain = 'catroweb';
    $locale_with_underscore = $this->sanitizeLocale($locale);
    $this->used_locale = $locale_with_underscore;

    try {
      return $this->translator->trans($id, $parameter, $domain, $locale_with_underscore);
    } catch (Exception $e) {
      // The format of $locale_with_underscore is correct, however we don't support this regional code yet.
      // Therefore we must use another regional code of this locale.
      $two_letter_code = $this->mapLocaleWithUnderscoreToTwoLetterCode($locale_with_underscore);
      $locale_with_underscore = $this->mapTwoLetterCodeToLocaleWithUnderscore($two_letter_code);
      $this->used_locale = $locale_with_underscore;

      return $this->translator->trans($id, $parameter, $domain, $locale_with_underscore);
    }
  }

  public function sanitizeLocale(?string $locale = null): string
  {
    $locale = trim($locale);
    if ('' === $locale) {
      return $this->getLocaleFallback();
    }

    // Remove trailing noise
    $locale = explode(' ', $locale)[0];

    $locale = $this->mapLocaleToLocaleWithUnderscore($locale);

    if ($this->isLocaleAValidLocaleWithUnderscore($locale)) {
      return $locale;
    }

    if ($this->isLocaleAValidTwoLetterLocale($locale)) {
      // We don't support 2 letter codes natively in our filesystem, therefore we must map them first

      return $this->mapTwoLetterCodeToLocaleWithUnderscore($locale);
    }

    return $this->getLocaleFallback();
  }

  public function isLocaleAValidLocaleWithUnderscore(string $locale): bool
  {
    return 1 === preg_match('/^([a-z]{2,3})(_[A-Z]+)$/', $locale);
  }

  public function isLocaleAValidTwoLetterLocale(string $locale): bool
  {
    return 1 === preg_match('/^([a-z]{2,3})$/', $locale);
  }

  public function mapLocaleToLocaleWithUnderscore(string $locale): string
  {
    return str_replace('-', '_', $locale);
  }

  public function mapLocaleWithUnderscoreToTwoLetterCode(string $locale_with_underscore): string
  {
    return explode('_', $locale_with_underscore)[0];
  }

  /**
   * There is no need to generate the mapping on every request.
   * In case new locales are added this mapping should be updated manually.
   *
   * Python code:
   * ```
   * import os
   * my_dir = os.listdir(r"PATH_TO_DIR_REPLACE!")
   * my_dir.sort()
   * for item in my_dir:
   * locale_with_underscore = (item.split('.'))[1]
   * two_letter_code = (locale_with_underscore.split('_'))[0]
   * print("case '" + two_letter_code + "':")
   * print("  return '" + locale_with_underscore + "';")
   * ```
   *
   * @return string locale_with_underscore
   */
  public function mapTwoLetterCodeToLocaleWithUnderscore(string $two_letter_code): string
  {
    switch ($two_letter_code) {
      // Custom Mapping to provide better translations
      case 'en':
        return 'en_UK';
      case 'pt':
        return 'pt_BR';

      // Autogenerated mapping without Custom:
      case 'af':
        return 'af_ZA';
      case 'ar':
        return 'ar_SA';
      case 'az':
        return 'az_AZ';
      case 'bg':
        return 'bg_BG';
      case 'bn':
        return 'bn_BD';
      case 'bs':
        return 'bs_BA';
      case 'ca':
        return 'ca_ES';
      case 'chr':
        return 'chr_US';
      case 'cs':
        return 'cs_CZ';
      case 'da':
        return 'da_DK';
      case 'de':
        return 'de_DE';
      case 'el':
        return 'el_GR';
      case 'es':
        return 'es_ES';
      case 'fa':
        return 'fa_AF';
      case 'fi':
        return 'fi_FI';
      case 'fr':
        return 'fr_FR';
      case 'gl':
        return 'gl_ES';
      case 'gu':
        return 'gu_IN';
      case 'ha':
        return 'ha_HG';
      case 'he':
        return 'he_IL';
      case 'hi':
        return 'hi_IN';
      case 'hr':
        return 'hr_HR';
      case 'hu':
        return 'hu_HU';
      case 'id':
        return 'id_ID';
      case 'ig':
        return 'ig_NG';
      case 'it':
        return 'it_IT';
      case 'ja':
        return 'ja_JP';
      case 'ka':
        return 'ka_GE';
      case 'kab':
        return 'kab_KAB';
      case 'kk':
        return 'kk_KZ';
      case 'kn':
        return 'kn_IN';
      case 'ko':
        return 'ko_KR';
      case 'lt':
        return 'lt_LT';
      case 'mk':
        return 'mk_MK';
      case 'ml':
        return 'ml_IN';
      case 'ms':
        return 'ms_MY';
      case 'nl':
        return 'nl_NL';
      case 'no':
        return 'no_NO';
      case 'pl':
        return 'pl_PL';
      case 'ps':
        return 'ps_AF';
      case 'ro':
        return 'ro_RO';
      case 'ru':
        return 'ru_RU';
      case 'sd':
        return 'sd_PK';
      case 'si':
        return 'si_LK';
      case 'sk':
        return 'sk_SK';
      case 'sl':
        return 'sl_SI';
      case 'sq':
        return 'sq_AL';
      case 'sr':
        return 'sr_Latn';
      case 'sv':
        return 'sv_SE';
      case 'sw':
        return 'sw_KE';
      case 'ta':
        return 'ta_IN';
      case 'te':
        return 'te_IN';
      case 'th':
        return 'th_TH';
      case 'tl':
        return 'tl_PH';
      case 'tr':
        return 'tr_TR';
      case 'tw':
        return 'tw_TW';
      case 'uk':
        return 'uk_UA';
      case 'ur':
        return 'ur_PK';
      case 'uz':
        return 'uz_UZ';
      case 'vi':
        return 'vi_VN';
      case 'zh':
        return 'zh_CN';
    }

    return $this->getLocaleFallback();
  }

  public function getUsedLocale(): string
  {
    return $this->used_locale ?? $this->getLocaleFallback();
  }

  public function getLocaleFallback(): string
  {
    return 'en';
  }
}
