imports:
    - { resource: config.yml }
    - { resource: parameters_dev.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: ['upload', 'download_stats']
    handlers:
        upload:
            type: stream
            path: %kernel.logs_dir%/upload.log
            level: error
            channels: [upload]
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: info
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        download_stats:
            type:  rotating_file
            path:  %kernel.logs_dir%/download_stats/download_stats.log
            level: info
            max_files: 20
            channels: [download_stats]

assetic:
    use_controller: true
    debug:          true
    
#bc_bootstrap:
#    less_filter: lessphp
#    jquery_path: "%kernel.root_dir%/Resources/public/js/jquery-1.10.1.js"

#swiftmailer:
#    delivery_address: me@example.com
