catroweb_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation

catroweb_web:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

catroweb_ci:
    resource: "@AppBundle/Controller/Ci"
    type:     annotation

catroweb_download:
    resource: "@AppBundle/Controller/DownloadProgramController.php"
    type:     annotation

mediapackage_download:
    resource: "@AppBundle/Controller/DownloadMediaPackageController.php"
    type:     annotation

backup_download:
    resource: "@AppBundle/Controller/DownloadBackupController.php"
    type:     annotation

catroweb_token_login:
    resource: "@AppBundle/Controller/Security/TokenLoginController.php"
    type:     annotation


login:
    path:      login
    defaults:  { _controller: FOSUserBundle:Security:login }

logout:
    path: logout
    defaults:  { _controller: AppBundle:Security\Logout:logout }
    
sonata_user_resetting:
    resource: "./sonata/sonata_resetting_1.xml"
    prefix: /resetting
    prefix: /catroid/resetting #app-hack
    
catrobat_web_hourOfCode_index:
    path: /hourOfCode/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: "https://share.catrob.at/pocketcode/help"

catrobat_web_hourOfCode:
    path: /hourOfCode/{page}
    defaults:
        page: 0
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: "https://share.catrob.at/pocketcode/help"

catrobat_web_hour_of_code_index:
    path: /hour-of-code/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: "https://share.catrob.at/pocketcode/help"

catrobat_web_hour_of_code:
    path: /hour-of-code/{page}
    defaults:
        page: 0
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: "https://share.catrob.at/pocketcode/help"

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /middleware_register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user_profile_show:
    pattern: /myprofile
    defaults: { _controller: "AppBundle:Web/Profile:profile", "id": 0 }

fos_user_profile_show:
    pattern: /myprofile
    defaults: { _controller: "AppBundle:Web/Profile:profile", "id": 0 }

