parameters:
     catrobat.test.directory.source: "%kernel.root_dir%/../testdata/DataFixtures/test.catrobat"
     catrobat.test.directory.source.extensions: "%kernel.root_dir%/../testdata/DataFixtures/extensions.catrobat"
     catrobat.test.directory.target: "%kernel.root_dir%/../testdata/DataFixtures/GeneratedFixtures/"
     jenkins:
        url: https://jenkins.catrob.at/buildByToken/buildWithParameters
        job: "Build-Program"
        token: "SECRETTOKEN"
        id_parameter_name: "PROJECT"
        download_url_parameter_name: "download"
        upload_url_paramenter: "upload"
        uploadtoken: "UPLOADTOKEN"
services:
    catrobat.test.command.generatetestdata:
        class: Catrobat\AppBundle\Commands\GenerateTestDataCommand
        arguments: ["@catrobat.test.filesystem", "@catrobat.test.extractor", "@catrobat.test.compressor", "%catrobat.test.directory.source%","%catrobat.test.directory.target%","%catrobat.test.directory.source.extensions%"]
        tags:
            -  { name: console.command }

    catrobat.test.filesystem:
        class: Symfony\Component\Filesystem\Filesystem
        public: false

    catrobat.test.extractor:
        class: Catrobat\AppBundle\Services\CatrobatFileExtractor
        arguments: ["%catrobat.test.directory.target%","%catrobat.file.extract.path%"]

    catrobat.test.compressor:
        class: Catrobat\AppBundle\Services\CatrobatFileCompressor

    tokengenerator.inner:
        class: Catrobat\AppBundle\Services\TokenGenerator

    tokengenerator:
        class: Catrobat\AppBundle\Services\TestEnv\ProxyTokenGenerator
        arguments: ["@tokengenerator.inner"]

    time.inner:
        class:        Catrobat\AppBundle\Services\Time

    time:
        class:  Catrobat\AppBundle\Services\TestEnv\ProxyTime
        arguments: ["@time.inner"]
        
    ci.jenkins.dispatcher:
        class: Catrobat\AppBundle\Features\Helpers\FakeJenkinsDispatcher
        arguments: 
          - "@router" 
          - "%jenkins%"

    fr3d_ldap.ldap_driver:
        class: Catrobat\AppBundle\Services\TestEnv\LdapTestDriver
        arguments:
          - "%ldap_base_dn%"
          
    facebook_post_service:
        class: Catrobat\AppBundle\Features\Helpers\FakeFacebookPostService
        arguments: ["@real_facebook_post_service"]

    real_facebook_post_service:
        class: Catrobat\AppBundle\Services\FacebookPostService
        arguments: ["@router", "@service_container", "@screenshotrepository"]

    real_oauth_service:
        class: Catrobat\AppBundle\Services\OAuthService
        arguments:
          - "@service_container"

    oauth_service:
        class: Catrobat\AppBundle\Features\Helpers\FakeOAuthService
        arguments: ["@real_oauth_service", "@service_container"]

    download_statistics:
        class: Catrobat\AppBundle\Features\Helpers\FakeDownloadStatisticsService
        arguments: ["@real_download_statistics"]

    real_download_statistics:
        class: Catrobat\AppBundle\Services\DownloadStatisticsService
        arguments:
          - "@programmanager"
          - "@doctrine.orm.entity_manager"
          - "@bazinga_geocoder.geocoder"
          - "@logger"
        tags:
          - { name: monolog.logger, channel: download_stats }
