@web @project_page
Feature: As a visitor I want to see code statistics on the project page

  Scenario: On a project page there should be correct stats for all code bricks
    Given I have a project zip "CodeStatistics/code_statistics_compound_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "COMPOUND2"
    And the "#brick-statistic-block-event .total-brick-statistic" element should not contain "0"
    And the "#brick-statistic-block-event .different-brick-statistic" element should not contain "0"
    And the "#brick-statistic-block-control .total-brick-statistic" element should not contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should not contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should not contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should not contain "0"
    But the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "7"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "6"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "6"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats
    Given I have a project zip "CodeStatistics/code_statistics_compound_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "COMPOUND2"
    And the "#scene-statistics" element should contain "1"
    But the "#scene-statistics" element should not contain "0"
    And the "#script-statistics" element should contain "1"
    But the "#script-statistics" element should not contain "0"
    And the "#brick-statistics" element should contain "14"
    But the "#brick-statistics" element should not contain "0"
    And the "#object-statistics" element should contain "1"
    But the "#object-statistics" element should not contain "0"
    And the "#look-statistics" element should contain "0"
    But the "#look-statistics" element should not contain "1"
    And the "#sound-statistics" element should contain "0"
    But the "#sound-statistics" element should not contain "3"
    And the "#global-variable-statistics" element should contain "0"
    But the "#global-variable-statistics" element should not contain "3"
    And the "#local-variable-statistics" element should contain "0"
    But the "#local-variable-statistics" element should not contain "7"

  Scenario: On a project page there should be correct stats
    Given I have a project zip "CodeStatistics/code_statistics_mixed_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "CODESTATS"
    And the "#scene-statistics" element should contain "2"
    And the "#script-statistics" element should contain "12"
    And the "#brick-statistics" element should contain "80"
    And the "#object-statistics" element should contain "7"
    And the "#look-statistics" element should contain "10"
    And the "#sound-statistics" element should contain "5"
    And the "#global-variable-statistics" element should contain "2"
    And the "#local-variable-statistics" element should contain "2"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "12"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "5"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "31"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "10"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "14"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "7"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "5"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "4"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "2"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "12"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "7"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about local and global vars
    Given I have a project zip "CodeStatistics/code_statistics_global_vs_local_variables.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "LOCALVSGLOBAL"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "2"
    And the "#brick-statistics" element should contain "9"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "1"
    And the "#local-variable-statistics" element should contain "4"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "2"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "2"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "7"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "2"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all event bricks
    Given I have a project zip "CodeStatistics/code_statistics_event_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "ALLEVENTS"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "8"
    And the "#brick-statistics" element should contain "10"
    And the "#object-statistics" element should contain "3"
    And the "#look-statistics" element should contain "2"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "8"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "8"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all control bricks
    Given I have a project zip "CodeStatistics/code_statistics_control_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "ALLCONTROLS"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "18"
    And the "#object-statistics" element should contain "1"
    And the "#look-statistics" element should contain "0"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "18"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "15"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all motion bricks
    Given I have a project zip "CodeStatistics/code_statistics_motion_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "ALLMOTION"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "23"
    And the "#object-statistics" element should contain "1"
    And the "#look-statistics" element should contain "0"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "22"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "22"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all sound bricks
    Given I have a project zip "CodeStatistics/code_statistics_sound_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "ALLSOUNDS"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "9"
    And the "#object-statistics" element should contain "1"
    And the "#look-statistics" element should contain "0"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "8"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "8"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all look bricks
    Given I have a project zip "CodeStatistics/code_statistics_look_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "ALLLOOKS"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "22"
    And the "#object-statistics" element should contain "1"
    And the "#look-statistics" element should contain "0"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "21"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "21"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all look bricks
    Given I have a project zip "CodeStatistics/code_statistics_pen_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "ALLPEN"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "7"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "6"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "6"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all look bricks
    Given I have a project zip "CodeStatistics/code_statistics_data_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "ALLDATA"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "14"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "13"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "13"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"


  Scenario: On a project page there should be correct stats about all arduino bricks
    Given I have a project zip "CodeStatistics/code_statistics_arduino_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "Arduino"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "3"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "2"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "2"

  Scenario: On a project page there should be correct stats about all lego ev3 bricks
    Given I have a project zip "CodeStatistics/code_statistics_lego_ev3_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "LEGO EV3"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "6"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "5"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "5"

  Scenario: On a project page there should be correct stats about all lego nxt bricks
    Given I have a project zip "CodeStatistics/code_statistics_lego_nxt_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "LEGONXT"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "5"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "4"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "4"

  Scenario: On a project page there should be correct stats about all embroidery bricks
    Given I have a project zip "CodeStatistics/code_statistics_embroidery_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "Embroidery"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "2"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "1"

  Scenario: On a project page there should be correct stats about all extended embroidery bricks
    Given I have a project zip "CodeStatistics/code_statistics_embroidery_blocks_extended.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "Embroidery"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "6"
    And the "#object-statistics" element should contain "1"
    And the "#look-statistics" element should contain "0"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "5"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "5"

  Scenario: On a project page there should be correct stats about all ar drone bricks
    Given I have a project zip "CodeStatistics/code_statistics_ar_drone_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "ARDRONE"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "14"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "12"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "12"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all jumping sumo bricks
    Given I have a project zip "CodeStatistics/code_statistics_jumping_sumo_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "SUMO"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "12"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "11"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "11"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all raspberry pi bricks
    Given I have a project zip "CodeStatistics/code_statistics_raspberrypi_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "RASBPERRYPI"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "6"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "2"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "2"

  Scenario: On a project page there should be correct stats about all nfc bricks
    Given I have a project zip "CodeStatistics/code_statistics_nfc_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "nfc"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "2"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "0"

  Scenario: On a project page there should be correct stats about all phiro bricks
    Given I have a project zip "CodeStatistics/code_statistics_phiro_blocks.catrobat"
    When I upload this project with id "1"
    Given I am on "/app/project/1"
    And I wait for the page to be loaded
    Then I should see "phiro"
    And the "#scene-statistics" element should contain "1"
    And the "#script-statistics" element should contain "1"
    And the "#brick-statistics" element should contain "15"
    And the "#object-statistics" element should contain "2"
    And the "#look-statistics" element should contain "1"
    And the "#sound-statistics" element should contain "0"
    And the "#global-variable-statistics" element should contain "0"
    And the "#local-variable-statistics" element should contain "0"
    And the "#brick-statistic-block-event .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-event .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-control .total-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-control .different-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-motion .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-motion .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-sound .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-sound .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-looks .total-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-looks .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-pen .total-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-pen .different-brick-statistic" element should contain "0"
    And the "#brick-statistic-block-data .total-brick-statistic" element should contain "6"
    And the "#brick-statistic-block-data .different-brick-statistic" element should contain "1"
    And the "#brick-statistic-block-special .total-brick-statistic" element should contain "3"
    And the "#brick-statistic-block-special .different-brick-statistic" element should contain "3"


