<?php

/**
 * AchievementsListResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the AchievementsListResponse model.
 *
 * @author  OpenAPI Generator team
 */
class AchievementsListResponse
{
  /**
   * @var AchievementResponse[]|null
   *
   * @SerializedName("unlocked")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\AchievementResponse")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\AchievementResponse>")
   */
  protected ?array $unlocked = null;

  /**
   * @var AchievementResponse[]|null
   *
   * @SerializedName("locked")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\AchievementResponse")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\AchievementResponse>")
   */
  protected ?array $locked = null;

  /**
   * @SerializedName("most_recent")
   *
   * @Assert\Type("OpenAPI\Server\Model\AchievementResponse")
   *
   * @Type("OpenAPI\Server\Model\AchievementResponse")
   */
  protected ?AchievementResponse $most_recent = null;

  /**
   * Date when the most recent achievement was unlocked (Y-m-d).
   *
   * @SerializedName("most_recent_unlocked_at")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $most_recent_unlocked_at = null;

  /**
   * Whether to show the new achievement animation.
   *
   * @SerializedName("show_animation")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $show_animation = null;

  /**
   * Total number of enabled achievements.
   *
   * @SerializedName("total_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $total_count = null;

  /**
   * Number of achievements unlocked by this user.
   *
   * @SerializedName("unlocked_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $unlocked_count = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->unlocked = array_key_exists('unlocked', $data) ? $data['unlocked'] : $this->unlocked;
      $this->locked = array_key_exists('locked', $data) ? $data['locked'] : $this->locked;
      $this->most_recent = array_key_exists('most_recent', $data) ? $data['most_recent'] : $this->most_recent;
      $this->most_recent_unlocked_at = array_key_exists('most_recent_unlocked_at', $data) ? $data['most_recent_unlocked_at'] : $this->most_recent_unlocked_at;
      $this->show_animation = array_key_exists('show_animation', $data) ? $data['show_animation'] : $this->show_animation;
      $this->total_count = array_key_exists('total_count', $data) ? $data['total_count'] : $this->total_count;
      $this->unlocked_count = array_key_exists('unlocked_count', $data) ? $data['unlocked_count'] : $this->unlocked_count;
    }
  }

  /**
   * Gets unlocked.
   *
   * @return AchievementResponse[]|null
   */
  public function getUnlocked(): ?array
  {
    return $this->unlocked;
  }

  /**
   * Sets unlocked.
   *
   * @param AchievementResponse[]|null $unlocked
   *
   * @return $this
   */
  public function setUnlocked(?array $unlocked = null): self
  {
    $this->unlocked = $unlocked;

    return $this;
  }

  /**
   * Gets locked.
   *
   * @return AchievementResponse[]|null
   */
  public function getLocked(): ?array
  {
    return $this->locked;
  }

  /**
   * Sets locked.
   *
   * @param AchievementResponse[]|null $locked
   *
   * @return $this
   */
  public function setLocked(?array $locked = null): self
  {
    $this->locked = $locked;

    return $this;
  }

  /**
   * Gets most_recent.
   */
  public function getMostRecent(): ?AchievementResponse
  {
    return $this->most_recent;
  }

  /**
   * Sets most_recent.
   *
   * @return $this
   */
  public function setMostRecent(?AchievementResponse $most_recent = null): self
  {
    $this->most_recent = $most_recent;

    return $this;
  }

  /**
   * Gets most_recent_unlocked_at.
   */
  public function getMostRecentUnlockedAt(): ?string
  {
    return $this->most_recent_unlocked_at;
  }

  /**
   * Sets most_recent_unlocked_at.
   *
   * @param string|null $most_recent_unlocked_at Date when the most recent achievement was unlocked (Y-m-d)
   *
   * @return $this
   */
  public function setMostRecentUnlockedAt(?string $most_recent_unlocked_at = null): self
  {
    $this->most_recent_unlocked_at = $most_recent_unlocked_at;

    return $this;
  }

  /**
   * Gets show_animation.
   */
  public function isShowAnimation(): ?bool
  {
    return $this->show_animation;
  }

  /**
   * Sets show_animation.
   *
   * @param bool|null $show_animation Whether to show the new achievement animation
   *
   * @return $this
   */
  public function setShowAnimation(?bool $show_animation = null): self
  {
    $this->show_animation = $show_animation;

    return $this;
  }

  /**
   * Gets total_count.
   */
  public function getTotalCount(): ?int
  {
    return $this->total_count;
  }

  /**
   * Sets total_count.
   *
   * @param int|null $total_count Total number of enabled achievements
   *
   * @return $this
   */
  public function setTotalCount(?int $total_count = null): self
  {
    $this->total_count = $total_count;

    return $this;
  }

  /**
   * Gets unlocked_count.
   */
  public function getUnlockedCount(): ?int
  {
    return $this->unlocked_count;
  }

  /**
   * Sets unlocked_count.
   *
   * @param int|null $unlocked_count Number of achievements unlocked by this user
   *
   * @return $this
   */
  public function setUnlockedCount(?int $unlocked_count = null): self
  {
    $this->unlocked_count = $unlocked_count;

    return $this;
  }
}
