<?php

/**
 * CodeViewResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the CodeViewResponse model.
 *
 * @author  OpenAPI Generator team
 */
class CodeViewResponse
{
  /**
   * @var CodeViewScene[]|null
   *
   * @SerializedName("scenes")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\CodeViewScene")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\CodeViewScene>")
   */
  protected ?array $scenes = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->scenes = array_key_exists('scenes', $data) ? $data['scenes'] : $this->scenes;
    }
  }

  /**
   * Gets scenes.
   *
   * @return CodeViewScene[]|null
   */
  public function getScenes(): ?array
  {
    return $this->scenes;
  }

  /**
   * Sets scenes.
   *
   * @param CodeViewScene[]|null $scenes
   *
   * @return $this
   */
  public function setScenes(?array $scenes = null): self
  {
    $this->scenes = $scenes;

    return $this;
  }
}
