<?php

/**
 * CodeViewObject.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the CodeViewObject model.
 *
 * @author  OpenAPI Generator team
 */
class CodeViewObject
{
  /**
   * @SerializedName("name")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $name = null;

  /**
   * @SerializedName("is_group")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $is_group = null;

  /**
   * @var CodeViewScript[]|null
   *
   * @SerializedName("scripts")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\CodeViewScript")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\CodeViewScript>")
   */
  protected ?array $scripts = null;

  /**
   * @var CodeViewAsset[]|null
   *
   * @SerializedName("looks")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\CodeViewAsset")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\CodeViewAsset>")
   */
  protected ?array $looks = null;

  /**
   * @var CodeViewAsset[]|null
   *
   * @SerializedName("sounds")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\CodeViewAsset")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\CodeViewAsset>")
   */
  protected ?array $sounds = null;

  /**
   * Child objects if this is a group sprite.
   *
   * @var CodeViewObject[]|null
   *
   * @SerializedName("children")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\CodeViewObject")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\CodeViewObject>")
   */
  protected ?array $children = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
      $this->is_group = array_key_exists('is_group', $data) ? $data['is_group'] : $this->is_group;
      $this->scripts = array_key_exists('scripts', $data) ? $data['scripts'] : $this->scripts;
      $this->looks = array_key_exists('looks', $data) ? $data['looks'] : $this->looks;
      $this->sounds = array_key_exists('sounds', $data) ? $data['sounds'] : $this->sounds;
      $this->children = array_key_exists('children', $data) ? $data['children'] : $this->children;
    }
  }

  /**
   * Gets name.
   */
  public function getName(): ?string
  {
    return $this->name;
  }

  /**
   * Sets name.
   *
   * @return $this
   */
  public function setName(?string $name = null): self
  {
    $this->name = $name;

    return $this;
  }

  /**
   * Gets is_group.
   */
  public function isIsGroup(): ?bool
  {
    return $this->is_group;
  }

  /**
   * Sets is_group.
   *
   * @return $this
   */
  public function setIsGroup(?bool $is_group = null): self
  {
    $this->is_group = $is_group;

    return $this;
  }

  /**
   * Gets scripts.
   *
   * @return CodeViewScript[]|null
   */
  public function getScripts(): ?array
  {
    return $this->scripts;
  }

  /**
   * Sets scripts.
   *
   * @param CodeViewScript[]|null $scripts
   *
   * @return $this
   */
  public function setScripts(?array $scripts = null): self
  {
    $this->scripts = $scripts;

    return $this;
  }

  /**
   * Gets looks.
   *
   * @return CodeViewAsset[]|null
   */
  public function getLooks(): ?array
  {
    return $this->looks;
  }

  /**
   * Sets looks.
   *
   * @param CodeViewAsset[]|null $looks
   *
   * @return $this
   */
  public function setLooks(?array $looks = null): self
  {
    $this->looks = $looks;

    return $this;
  }

  /**
   * Gets sounds.
   *
   * @return CodeViewAsset[]|null
   */
  public function getSounds(): ?array
  {
    return $this->sounds;
  }

  /**
   * Sets sounds.
   *
   * @param CodeViewAsset[]|null $sounds
   *
   * @return $this
   */
  public function setSounds(?array $sounds = null): self
  {
    $this->sounds = $sounds;

    return $this;
  }

  /**
   * Gets children.
   *
   * @return CodeViewObject[]|null
   */
  public function getChildren(): ?array
  {
    return $this->children;
  }

  /**
   * Sets children.
   *
   * @param CodeViewObject[]|null $children Child objects if this is a group sprite
   *
   * @return $this
   */
  public function setChildren(?array $children = null): self
  {
    $this->children = $children;

    return $this;
  }
}
