<?php

/**
 * CommentCreateRequest.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the CommentCreateRequest model.
 *
 * @author  OpenAPI Generator team
 */
class CommentCreateRequest
{
  /**
   * Comment text.
   *
   * @SerializedName("message")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $message = null;

  /**
   * Parent comment UUID for replies.
   *
   * @SerializedName("parent_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $parent_id = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->message = array_key_exists('message', $data) ? $data['message'] : $this->message;
      $this->parent_id = array_key_exists('parent_id', $data) ? $data['parent_id'] : $this->parent_id;
    }
  }

  /**
   * Gets message.
   */
  public function getMessage(): ?string
  {
    return $this->message;
  }

  /**
   * Sets message.
   *
   * @param string|null $message Comment text
   *
   * @return $this
   */
  public function setMessage(?string $message): self
  {
    $this->message = $message;

    return $this;
  }

  /**
   * Gets parent_id.
   */
  public function getParentId(): ?string
  {
    return $this->parent_id;
  }

  /**
   * Sets parent_id.
   *
   * @param string|null $parent_id Parent comment UUID for replies
   *
   * @return $this
   */
  public function setParentId(?string $parent_id = null): self
  {
    $this->parent_id = $parent_id;

    return $this;
  }
}
