<?php

/**
 * CommentResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the CommentResponse model.
 *
 * @author  OpenAPI Generator team
 */
class CommentResponse
{
  /**
   * Unique ID of the comment.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $id = null;

  /**
   * Unique UUID/ID (string) of the object.
   *
   * @SerializedName("project_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   *
   * @Assert\Regex("/^[a-zA-Z0-9\\-]+$/")
   */
  protected ?string $project_id = null;

  /**
   * Unique ID of the comment.
   *
   * @SerializedName("parent_id")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $parent_id = null;

  /**
   * @SerializedName("user")
   *
   * @Assert\Type("OpenAPI\Server\Model\CommentUserInfo")
   *
   * @Type("OpenAPI\Server\Model\CommentUserInfo")
   */
  protected ?CommentUserInfo $user = null;

  /**
   * Comment text (null if deleted).
   *
   * @SerializedName("message")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $message = null;

  /**
   * @SerializedName("created_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $created_at = null;

  /**
   * @SerializedName("reply_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $reply_count = null;

  /**
   * @SerializedName("is_deleted")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $is_deleted = null;

  /**
   * @SerializedName("is_reported")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $is_reported = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->project_id = array_key_exists('project_id', $data) ? $data['project_id'] : $this->project_id;
      $this->parent_id = array_key_exists('parent_id', $data) ? $data['parent_id'] : $this->parent_id;
      $this->user = array_key_exists('user', $data) ? $data['user'] : $this->user;
      $this->message = array_key_exists('message', $data) ? $data['message'] : $this->message;
      $this->created_at = array_key_exists('created_at', $data) ? $data['created_at'] : $this->created_at;
      $this->reply_count = array_key_exists('reply_count', $data) ? $data['reply_count'] : $this->reply_count;
      $this->is_deleted = array_key_exists('is_deleted', $data) ? $data['is_deleted'] : $this->is_deleted;
      $this->is_reported = array_key_exists('is_reported', $data) ? $data['is_reported'] : $this->is_reported;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?int
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param int|null $id Unique ID of the comment
   *
   * @return $this
   */
  public function setId(?int $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets project_id.
   */
  public function getProjectId(): ?string
  {
    return $this->project_id;
  }

  /**
   * Sets project_id.
   *
   * @param string|null $project_id Unique UUID/ID (string) of the object
   *
   * @return $this
   */
  public function setProjectId(?string $project_id = null): self
  {
    $this->project_id = $project_id;

    return $this;
  }

  /**
   * Gets parent_id.
   */
  public function getParentId(): ?int
  {
    return $this->parent_id;
  }

  /**
   * Sets parent_id.
   *
   * @param int|null $parent_id Unique ID of the comment
   *
   * @return $this
   */
  public function setParentId(?int $parent_id = null): self
  {
    $this->parent_id = $parent_id;

    return $this;
  }

  /**
   * Gets user.
   */
  public function getUser(): ?CommentUserInfo
  {
    return $this->user;
  }

  /**
   * Sets user.
   *
   * @return $this
   */
  public function setUser(?CommentUserInfo $user = null): self
  {
    $this->user = $user;

    return $this;
  }

  /**
   * Gets message.
   */
  public function getMessage(): ?string
  {
    return $this->message;
  }

  /**
   * Sets message.
   *
   * @param string|null $message Comment text (null if deleted)
   *
   * @return $this
   */
  public function setMessage(?string $message = null): self
  {
    $this->message = $message;

    return $this;
  }

  /**
   * Gets created_at.
   */
  public function getCreatedAt(): ?\DateTime
  {
    return $this->created_at;
  }

  /**
   * Sets created_at.
   *
   * @return $this
   */
  public function setCreatedAt(?\DateTime $created_at = null): self
  {
    $this->created_at = $created_at;

    return $this;
  }

  /**
   * Gets reply_count.
   */
  public function getReplyCount(): ?int
  {
    return $this->reply_count;
  }

  /**
   * Sets reply_count.
   *
   * @return $this
   */
  public function setReplyCount(?int $reply_count = null): self
  {
    $this->reply_count = $reply_count;

    return $this;
  }

  /**
   * Gets is_deleted.
   */
  public function isIsDeleted(): ?bool
  {
    return $this->is_deleted;
  }

  /**
   * Sets is_deleted.
   *
   * @return $this
   */
  public function setIsDeleted(?bool $is_deleted = null): self
  {
    $this->is_deleted = $is_deleted;

    return $this;
  }

  /**
   * Gets is_reported.
   */
  public function isIsReported(): ?bool
  {
    return $this->is_reported;
  }

  /**
   * Sets is_reported.
   *
   * @return $this
   */
  public function setIsReported(?bool $is_reported = null): self
  {
    $this->is_reported = $is_reported;

    return $this;
  }
}
