<?php

/**
 * ContentReportRequest.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the ContentReportRequest model.
 *
 * @author  OpenAPI Generator team
 */
class ContentReportRequest
{
  /**
   * Report reason category.
   *
   * @SerializedName("category")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $category = null;

  /**
   * Optional additional details.
   *
   * @SerializedName("note")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   *
   * @Assert\Length(
   *   max = 5000
   * )
   */
  protected ?string $note = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->category = array_key_exists('category', $data) ? $data['category'] : $this->category;
      $this->note = array_key_exists('note', $data) ? $data['note'] : $this->note;
    }
  }

  /**
   * Gets category.
   */
  public function getCategory(): ?string
  {
    return $this->category;
  }

  /**
   * Sets category.
   *
   * @param string|null $category Report reason category
   *
   * @return $this
   */
  public function setCategory(?string $category): self
  {
    $this->category = $category;

    return $this;
  }

  /**
   * Gets note.
   */
  public function getNote(): ?string
  {
    return $this->note;
  }

  /**
   * Sets note.
   *
   * @param string|null $note Optional additional details
   *
   * @return $this
   */
  public function setNote(?string $note = null): self
  {
    $this->note = $note;

    return $this;
  }
}
