<?php

/**
 * ErrorResponseErrorDetailsInner.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the ErrorResponseErrorDetailsInner model.
 *
 * @author  OpenAPI Generator team
 */
class ErrorResponseErrorDetailsInner
{
  /**
   * The field that caused the error.
   *
   * @SerializedName("field")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $field = null;

  /**
   * Human-readable error message for this field.
   *
   * @SerializedName("message")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $message = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->field = array_key_exists('field', $data) ? $data['field'] : $this->field;
      $this->message = array_key_exists('message', $data) ? $data['message'] : $this->message;
    }
  }

  /**
   * Gets field.
   */
  public function getField(): ?string
  {
    return $this->field;
  }

  /**
   * Sets field.
   *
   * @param string|null $field The field that caused the error
   *
   * @return $this
   */
  public function setField(?string $field): self
  {
    $this->field = $field;

    return $this;
  }

  /**
   * Gets message.
   */
  public function getMessage(): ?string
  {
    return $this->message;
  }

  /**
   * Sets message.
   *
   * @param string|null $message Human-readable error message for this field
   *
   * @return $this
   */
  public function setMessage(?string $message): self
  {
    $this->message = $message;

    return $this;
  }
}
