<?php

/**
 * ErrorResponseError.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the ErrorResponseError model.
 *
 * @author  OpenAPI Generator team
 */
class ErrorResponseError
{
  /**
   * HTTP status code.
   *
   * @SerializedName("code")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $code = null;

  /**
   * Machine-readable error type.
   *
   * @SerializedName("type")
   *
   * @Assert\NotNull()
   *
   * @Assert\Choice({ "validation_error", "bad_request", "unauthorized", "forbidden", "not_found", "not_acceptable", "unsupported_media_type", "unprocessable_entity", "too_many_requests", "internal_error" })
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $type = null;

  /**
   * Human-readable error summary.
   *
   * @SerializedName("message")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $message = null;

  /**
   * Optional field-level error details (for validation errors).
   *
   * @var ErrorResponseErrorDetailsInner[]|null
   *
   * @SerializedName("details")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\ErrorResponseErrorDetailsInner")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\ErrorResponseErrorDetailsInner>")
   */
  protected ?array $details = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->code = array_key_exists('code', $data) ? $data['code'] : $this->code;
      $this->type = array_key_exists('type', $data) ? $data['type'] : $this->type;
      $this->message = array_key_exists('message', $data) ? $data['message'] : $this->message;
      $this->details = array_key_exists('details', $data) ? $data['details'] : $this->details;
    }
  }

  /**
   * Gets code.
   */
  public function getCode(): ?int
  {
    return $this->code;
  }

  /**
   * Sets code.
   *
   * @param int|null $code HTTP status code
   *
   * @return $this
   */
  public function setCode(?int $code): self
  {
    $this->code = $code;

    return $this;
  }

  /**
   * Gets type.
   */
  public function getType(): ?string
  {
    return $this->type;
  }

  /**
   * Sets type.
   *
   * @param string|null $type Machine-readable error type
   *
   * @return $this
   */
  public function setType(?string $type): self
  {
    $this->type = $type;

    return $this;
  }

  /**
   * Gets message.
   */
  public function getMessage(): ?string
  {
    return $this->message;
  }

  /**
   * Sets message.
   *
   * @param string|null $message Human-readable error summary
   *
   * @return $this
   */
  public function setMessage(?string $message): self
  {
    $this->message = $message;

    return $this;
  }

  /**
   * Gets details.
   *
   * @return ErrorResponseErrorDetailsInner[]|null
   */
  public function getDetails(): ?array
  {
    return $this->details;
  }

  /**
   * Sets details.
   *
   * @param ErrorResponseErrorDetailsInner[]|null $details Optional field-level error details (for validation errors)
   *
   * @return $this
   */
  public function setDetails(?array $details = null): self
  {
    $this->details = $details;

    return $this;
  }
}
