<?php

/**
 * FeaturedBannerResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the FeaturedBannerResponse model.
 *
 * @author  OpenAPI Generator team
 */
class FeaturedBannerResponse
{
  /**
   * Banner UUID.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * @SerializedName("type")
   *
   * @Assert\Choice({ "project", "studio", "link", "image", "video" })
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $type = null;

  /**
   * @SerializedName("title")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $title = null;

  /**
   * @SerializedName("image_variants")
   *
   * @Assert\Type("OpenAPI\Server\Model\ImageVariants")
   *
   * @Type("OpenAPI\Server\Model\ImageVariants")
   */
  protected ?ImageVariants $image_variants = null;

  /**
   * @SerializedName("link_url")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $link_url = null;

  /**
   * YouTube embed URL for video-type banners.
   *
   * @SerializedName("video_url")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $video_url = null;

  /**
   * @SerializedName("priority")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $priority = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->type = array_key_exists('type', $data) ? $data['type'] : $this->type;
      $this->title = array_key_exists('title', $data) ? $data['title'] : $this->title;
      $this->image_variants = array_key_exists('image_variants', $data) ? $data['image_variants'] : $this->image_variants;
      $this->link_url = array_key_exists('link_url', $data) ? $data['link_url'] : $this->link_url;
      $this->video_url = array_key_exists('video_url', $data) ? $data['video_url'] : $this->video_url;
      $this->priority = array_key_exists('priority', $data) ? $data['priority'] : $this->priority;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Banner UUID
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets type.
   */
  public function getType(): ?string
  {
    return $this->type;
  }

  /**
   * Sets type.
   *
   * @return $this
   */
  public function setType(?string $type = null): self
  {
    $this->type = $type;

    return $this;
  }

  /**
   * Gets title.
   */
  public function getTitle(): ?string
  {
    return $this->title;
  }

  /**
   * Sets title.
   *
   * @return $this
   */
  public function setTitle(?string $title = null): self
  {
    $this->title = $title;

    return $this;
  }

  /**
   * Gets image_variants.
   */
  public function getImageVariants(): ?ImageVariants
  {
    return $this->image_variants;
  }

  /**
   * Sets image_variants.
   *
   * @return $this
   */
  public function setImageVariants(?ImageVariants $image_variants = null): self
  {
    $this->image_variants = $image_variants;

    return $this;
  }

  /**
   * Gets link_url.
   */
  public function getLinkUrl(): ?string
  {
    return $this->link_url;
  }

  /**
   * Sets link_url.
   *
   * @return $this
   */
  public function setLinkUrl(?string $link_url = null): self
  {
    $this->link_url = $link_url;

    return $this;
  }

  /**
   * Gets video_url.
   */
  public function getVideoUrl(): ?string
  {
    return $this->video_url;
  }

  /**
   * Sets video_url.
   *
   * @param string|null $video_url YouTube embed URL for video-type banners
   *
   * @return $this
   */
  public function setVideoUrl(?string $video_url = null): self
  {
    $this->video_url = $video_url;

    return $this;
  }

  /**
   * Gets priority.
   */
  public function getPriority(): ?int
  {
    return $this->priority;
  }

  /**
   * Sets priority.
   *
   * @return $this
   */
  public function setPriority(?int $priority = null): self
  {
    $this->priority = $priority;

    return $this;
  }
}
