<?php

/**
 * FollowerResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the FollowerResponse model.
 *
 * @author  OpenAPI Generator team
 */
class FollowerResponse
{
  /**
   * Unique UUID/ID (string) of the object.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   *
   * @Assert\Regex("/^[a-zA-Z0-9\\-]+$/")
   */
  protected ?string $id = null;

  /**
   * @SerializedName("username")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $username = null;

  /**
   * User avatar URL.
   *
   * @SerializedName("avatar")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $avatar = null;

  /**
   * Number of public projects.
   *
   * @SerializedName("project_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $project_count = null;

  /**
   * Number of followers.
   *
   * @SerializedName("follower_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $follower_count = null;

  /**
   * Does the authenticated user follow this user?
   *
   * @SerializedName("is_following")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $is_following = null;

  /**
   * Does this user follow the authenticated user?
   *
   * @SerializedName("follows_you")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $follows_you = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->username = array_key_exists('username', $data) ? $data['username'] : $this->username;
      $this->avatar = array_key_exists('avatar', $data) ? $data['avatar'] : $this->avatar;
      $this->project_count = array_key_exists('project_count', $data) ? $data['project_count'] : $this->project_count;
      $this->follower_count = array_key_exists('follower_count', $data) ? $data['follower_count'] : $this->follower_count;
      $this->is_following = array_key_exists('is_following', $data) ? $data['is_following'] : $this->is_following;
      $this->follows_you = array_key_exists('follows_you', $data) ? $data['follows_you'] : $this->follows_you;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Unique UUID/ID (string) of the object
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets username.
   */
  public function getUsername(): ?string
  {
    return $this->username;
  }

  /**
   * Sets username.
   *
   * @return $this
   */
  public function setUsername(?string $username = null): self
  {
    $this->username = $username;

    return $this;
  }

  /**
   * Gets avatar.
   */
  public function getAvatar(): ?string
  {
    return $this->avatar;
  }

  /**
   * Sets avatar.
   *
   * @param string|null $avatar User avatar URL
   *
   * @return $this
   */
  public function setAvatar(?string $avatar = null): self
  {
    $this->avatar = $avatar;

    return $this;
  }

  /**
   * Gets project_count.
   */
  public function getProjectCount(): ?int
  {
    return $this->project_count;
  }

  /**
   * Sets project_count.
   *
   * @param int|null $project_count Number of public projects
   *
   * @return $this
   */
  public function setProjectCount(?int $project_count = null): self
  {
    $this->project_count = $project_count;

    return $this;
  }

  /**
   * Gets follower_count.
   */
  public function getFollowerCount(): ?int
  {
    return $this->follower_count;
  }

  /**
   * Sets follower_count.
   *
   * @param int|null $follower_count Number of followers
   *
   * @return $this
   */
  public function setFollowerCount(?int $follower_count = null): self
  {
    $this->follower_count = $follower_count;

    return $this;
  }

  /**
   * Gets is_following.
   */
  public function isIsFollowing(): ?bool
  {
    return $this->is_following;
  }

  /**
   * Sets is_following.
   *
   * @param bool|null $is_following Does the authenticated user follow this user?
   *
   * @return $this
   */
  public function setIsFollowing(?bool $is_following = null): self
  {
    $this->is_following = $is_following;

    return $this;
  }

  /**
   * Gets follows_you.
   */
  public function isFollowsYou(): ?bool
  {
    return $this->follows_you;
  }

  /**
   * Sets follows_you.
   *
   * @param bool|null $follows_you Does this user follow the authenticated user?
   *
   * @return $this
   */
  public function setFollowsYou(?bool $follows_you = null): self
  {
    $this->follows_you = $follows_you;

    return $this;
  }
}
