<?php

/**
 * ImageVariantSet.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the ImageVariantSet model.
 *
 * A set of URLs for one logical image width (e.g. thumb/card/detail) in modern formats and device-pixel ratios. Clients should prefer AVIF and fall back to WebP. URLs are nullable when a given format is not available (e.g. AVIF when the encoder is missing).
 *
 * @author  OpenAPI Generator team
 */
class ImageVariantSet
{
  /**
   * AVIF encoded at 1x device-pixel ratio.
   *
   * @SerializedName("avif_1x")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $avif_1x = null;

  /**
   * AVIF encoded at 2x device-pixel ratio (retina).
   *
   * @SerializedName("avif_2x")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $avif_2x = null;

  /**
   * WebP encoded at 1x device-pixel ratio.
   *
   * @SerializedName("webp_1x")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $webp_1x = null;

  /**
   * WebP encoded at 2x device-pixel ratio (retina).
   *
   * @SerializedName("webp_2x")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $webp_2x = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->avif_1x = array_key_exists('avif_1x', $data) ? $data['avif_1x'] : $this->avif_1x;
      $this->avif_2x = array_key_exists('avif_2x', $data) ? $data['avif_2x'] : $this->avif_2x;
      $this->webp_1x = array_key_exists('webp_1x', $data) ? $data['webp_1x'] : $this->webp_1x;
      $this->webp_2x = array_key_exists('webp_2x', $data) ? $data['webp_2x'] : $this->webp_2x;
    }
  }

  /**
   * Gets avif_1x.
   */
  public function getAvif1x(): ?string
  {
    return $this->avif_1x;
  }

  /**
   * Sets avif_1x.
   *
   * @param string|null $avif_1x AVIF encoded at 1x device-pixel ratio
   *
   * @return $this
   */
  public function setAvif1x(?string $avif_1x = null): self
  {
    $this->avif_1x = $avif_1x;

    return $this;
  }

  /**
   * Gets avif_2x.
   */
  public function getAvif2x(): ?string
  {
    return $this->avif_2x;
  }

  /**
   * Sets avif_2x.
   *
   * @param string|null $avif_2x AVIF encoded at 2x device-pixel ratio (retina)
   *
   * @return $this
   */
  public function setAvif2x(?string $avif_2x = null): self
  {
    $this->avif_2x = $avif_2x;

    return $this;
  }

  /**
   * Gets webp_1x.
   */
  public function getWebp1x(): ?string
  {
    return $this->webp_1x;
  }

  /**
   * Sets webp_1x.
   *
   * @param string|null $webp_1x WebP encoded at 1x device-pixel ratio
   *
   * @return $this
   */
  public function setWebp1x(?string $webp_1x = null): self
  {
    $this->webp_1x = $webp_1x;

    return $this;
  }

  /**
   * Gets webp_2x.
   */
  public function getWebp2x(): ?string
  {
    return $this->webp_2x;
  }

  /**
   * Sets webp_2x.
   *
   * @param string|null $webp_2x WebP encoded at 2x device-pixel ratio (retina)
   *
   * @return $this
   */
  public function setWebp2x(?string $webp_2x = null): self
  {
    $this->webp_2x = $webp_2x;

    return $this;
  }
}
