<?php

/**
 * ImageVariants.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the ImageVariants model.
 *
 * Responsive image variants shared by studio covers, user avatars and project screenshots. Each property is an {@see ImageVariantSet} intended for a specific render context:   * &#x60;thumb&#x60;   ~ 96 CSS px  (comment/list avatars, small cards)   * &#x60;card&#x60;    ~ 320 CSS px (project tiles, search cards, profile hero)   * &#x60;detail&#x60;  ~ 960 CSS px (project detail, studio header, featured banner) Build a &#x60;&lt;picture&gt;&#x60; with &#x60;&lt;source type&#x3D;\&quot;image/avif\&quot;&gt;&#x60; then &#x60;&lt;source type&#x3D;\&quot;image/webp\&quot;&gt;&#x60; and a final &#x60;&lt;img&gt;&#x60; fallback to the WebP 1x URL, using &#x60;srcset&#x60; &#x60;\&quot;url 1x, url2 2x\&quot;&#x60; per set.
 *
 * @author  OpenAPI Generator team
 */
class ImageVariants
{
  /**
   * @SerializedName("thumb")
   *
   * @Assert\Type("OpenAPI\Server\Model\ImageVariantSet")
   *
   * @Type("OpenAPI\Server\Model\ImageVariantSet")
   */
  protected ?ImageVariantSet $thumb = null;

  /**
   * @SerializedName("card")
   *
   * @Assert\Type("OpenAPI\Server\Model\ImageVariantSet")
   *
   * @Type("OpenAPI\Server\Model\ImageVariantSet")
   */
  protected ?ImageVariantSet $card = null;

  /**
   * @SerializedName("detail")
   *
   * @Assert\Type("OpenAPI\Server\Model\ImageVariantSet")
   *
   * @Type("OpenAPI\Server\Model\ImageVariantSet")
   */
  protected ?ImageVariantSet $detail = null;

  /**
   * Original image width in pixels (useful as a CLS-safe layout hint).
   *
   * @SerializedName("width")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $width = null;

  /**
   * Original image height in pixels (useful as a CLS-safe layout hint).
   *
   * @SerializedName("height")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $height = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->thumb = array_key_exists('thumb', $data) ? $data['thumb'] : $this->thumb;
      $this->card = array_key_exists('card', $data) ? $data['card'] : $this->card;
      $this->detail = array_key_exists('detail', $data) ? $data['detail'] : $this->detail;
      $this->width = array_key_exists('width', $data) ? $data['width'] : $this->width;
      $this->height = array_key_exists('height', $data) ? $data['height'] : $this->height;
    }
  }

  /**
   * Gets thumb.
   */
  public function getThumb(): ?ImageVariantSet
  {
    return $this->thumb;
  }

  /**
   * Sets thumb.
   *
   * @return $this
   */
  public function setThumb(?ImageVariantSet $thumb = null): self
  {
    $this->thumb = $thumb;

    return $this;
  }

  /**
   * Gets card.
   */
  public function getCard(): ?ImageVariantSet
  {
    return $this->card;
  }

  /**
   * Sets card.
   *
   * @return $this
   */
  public function setCard(?ImageVariantSet $card = null): self
  {
    $this->card = $card;

    return $this;
  }

  /**
   * Gets detail.
   */
  public function getDetail(): ?ImageVariantSet
  {
    return $this->detail;
  }

  /**
   * Sets detail.
   *
   * @return $this
   */
  public function setDetail(?ImageVariantSet $detail = null): self
  {
    $this->detail = $detail;

    return $this;
  }

  /**
   * Gets width.
   */
  public function getWidth(): ?int
  {
    return $this->width;
  }

  /**
   * Sets width.
   *
   * @param int|null $width Original image width in pixels (useful as a CLS-safe layout hint)
   *
   * @return $this
   */
  public function setWidth(?int $width = null): self
  {
    $this->width = $width;

    return $this;
  }

  /**
   * Gets height.
   */
  public function getHeight(): ?int
  {
    return $this->height;
  }

  /**
   * Sets height.
   *
   * @param int|null $height Original image height in pixels (useful as a CLS-safe layout hint)
   *
   * @return $this
   */
  public function setHeight(?int $height = null): self
  {
    $this->height = $height;

    return $this;
  }
}
