<?php

/**
 * MediaAssetsResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the MediaAssetsResponse model.
 *
 * @author  OpenAPI Generator team
 */
class MediaAssetsResponse
{
  /**
   * @var MediaAssetResponse[]|null
   *
   * @SerializedName("assets")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\MediaAssetResponse")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\MediaAssetResponse>")
   */
  protected ?array $assets = null;

  /**
   * @SerializedName("pagination")
   *
   * @Assert\Type("OpenAPI\Server\Model\PaginationInfo")
   *
   * @Type("OpenAPI\Server\Model\PaginationInfo")
   */
  protected ?PaginationInfo $pagination = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->assets = array_key_exists('assets', $data) ? $data['assets'] : $this->assets;
      $this->pagination = array_key_exists('pagination', $data) ? $data['pagination'] : $this->pagination;
    }
  }

  /**
   * Gets assets.
   *
   * @return MediaAssetResponse[]|null
   */
  public function getAssets(): ?array
  {
    return $this->assets;
  }

  /**
   * Sets assets.
   *
   * @param MediaAssetResponse[]|null $assets
   *
   * @return $this
   */
  public function setAssets(?array $assets = null): self
  {
    $this->assets = $assets;

    return $this;
  }

  /**
   * Gets pagination.
   */
  public function getPagination(): ?PaginationInfo
  {
    return $this->pagination;
  }

  /**
   * Sets pagination.
   *
   * @return $this
   */
  public function setPagination(?PaginationInfo $pagination = null): self
  {
    $this->pagination = $pagination;

    return $this;
  }
}
