<?php

/**
 * MediaAssetResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the MediaAssetResponse model.
 *
 * @author  OpenAPI Generator team
 */
class MediaAssetResponse
{
  /**
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * @SerializedName("name")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $name = null;

  /**
   * @SerializedName("description")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $description = null;

  /**
   * @SerializedName("file_type")
   *
   * @Assert\Choice({ "IMAGE", "SOUND" })
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $file_type = null;

  /**
   * @SerializedName("extension")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $extension = null;

  /**
   * File size in bytes.
   *
   * @SerializedName("size")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $size = null;

  /**
   * @SerializedName("author")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $author = null;

  /**
   * @SerializedName("downloads")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $downloads = null;

  /**
   * @SerializedName("active")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $active = null;

  /**
   * @SerializedName("created_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $created_at = null;

  /**
   * @SerializedName("updated_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $updated_at = null;

  /**
   * Category UUID.
   *
   * @SerializedName("category_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $category_id = null;

  /**
   * Translated category name.
   *
   * @SerializedName("category_name")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $category_name = null;

  /**
   * @var string[]|null
   *
   * @SerializedName("flavors")
   *
   * @Assert\All({
   *
   *   @Assert\Type("string")
   * })
   *
   * @Type("array<string>")
   */
  protected ?array $flavors = null;

  /**
   * @SerializedName("download_url")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $download_url = null;

  /**
   * @SerializedName("thumbnail_url")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $thumbnail_url = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
      $this->description = array_key_exists('description', $data) ? $data['description'] : $this->description;
      $this->file_type = array_key_exists('file_type', $data) ? $data['file_type'] : $this->file_type;
      $this->extension = array_key_exists('extension', $data) ? $data['extension'] : $this->extension;
      $this->size = array_key_exists('size', $data) ? $data['size'] : $this->size;
      $this->author = array_key_exists('author', $data) ? $data['author'] : $this->author;
      $this->downloads = array_key_exists('downloads', $data) ? $data['downloads'] : $this->downloads;
      $this->active = array_key_exists('active', $data) ? $data['active'] : $this->active;
      $this->created_at = array_key_exists('created_at', $data) ? $data['created_at'] : $this->created_at;
      $this->updated_at = array_key_exists('updated_at', $data) ? $data['updated_at'] : $this->updated_at;
      $this->category_id = array_key_exists('category_id', $data) ? $data['category_id'] : $this->category_id;
      $this->category_name = array_key_exists('category_name', $data) ? $data['category_name'] : $this->category_name;
      $this->flavors = array_key_exists('flavors', $data) ? $data['flavors'] : $this->flavors;
      $this->download_url = array_key_exists('download_url', $data) ? $data['download_url'] : $this->download_url;
      $this->thumbnail_url = array_key_exists('thumbnail_url', $data) ? $data['thumbnail_url'] : $this->thumbnail_url;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets name.
   */
  public function getName(): ?string
  {
    return $this->name;
  }

  /**
   * Sets name.
   *
   * @return $this
   */
  public function setName(?string $name = null): self
  {
    $this->name = $name;

    return $this;
  }

  /**
   * Gets description.
   */
  public function getDescription(): ?string
  {
    return $this->description;
  }

  /**
   * Sets description.
   *
   * @return $this
   */
  public function setDescription(?string $description = null): self
  {
    $this->description = $description;

    return $this;
  }

  /**
   * Gets file_type.
   */
  public function getFileType(): ?string
  {
    return $this->file_type;
  }

  /**
   * Sets file_type.
   *
   * @return $this
   */
  public function setFileType(?string $file_type = null): self
  {
    $this->file_type = $file_type;

    return $this;
  }

  /**
   * Gets extension.
   */
  public function getExtension(): ?string
  {
    return $this->extension;
  }

  /**
   * Sets extension.
   *
   * @return $this
   */
  public function setExtension(?string $extension = null): self
  {
    $this->extension = $extension;

    return $this;
  }

  /**
   * Gets size.
   */
  public function getSize(): ?int
  {
    return $this->size;
  }

  /**
   * Sets size.
   *
   * @param int|null $size File size in bytes
   *
   * @return $this
   */
  public function setSize(?int $size = null): self
  {
    $this->size = $size;

    return $this;
  }

  /**
   * Gets author.
   */
  public function getAuthor(): ?string
  {
    return $this->author;
  }

  /**
   * Sets author.
   *
   * @return $this
   */
  public function setAuthor(?string $author = null): self
  {
    $this->author = $author;

    return $this;
  }

  /**
   * Gets downloads.
   */
  public function getDownloads(): ?int
  {
    return $this->downloads;
  }

  /**
   * Sets downloads.
   *
   * @return $this
   */
  public function setDownloads(?int $downloads = null): self
  {
    $this->downloads = $downloads;

    return $this;
  }

  /**
   * Gets active.
   */
  public function isActive(): ?bool
  {
    return $this->active;
  }

  /**
   * Sets active.
   *
   * @return $this
   */
  public function setActive(?bool $active = null): self
  {
    $this->active = $active;

    return $this;
  }

  /**
   * Gets created_at.
   */
  public function getCreatedAt(): ?\DateTime
  {
    return $this->created_at;
  }

  /**
   * Sets created_at.
   *
   * @return $this
   */
  public function setCreatedAt(?\DateTime $created_at = null): self
  {
    $this->created_at = $created_at;

    return $this;
  }

  /**
   * Gets updated_at.
   */
  public function getUpdatedAt(): ?\DateTime
  {
    return $this->updated_at;
  }

  /**
   * Sets updated_at.
   *
   * @return $this
   */
  public function setUpdatedAt(?\DateTime $updated_at = null): self
  {
    $this->updated_at = $updated_at;

    return $this;
  }

  /**
   * Gets category_id.
   */
  public function getCategoryId(): ?string
  {
    return $this->category_id;
  }

  /**
   * Sets category_id.
   *
   * @param string|null $category_id Category UUID
   *
   * @return $this
   */
  public function setCategoryId(?string $category_id = null): self
  {
    $this->category_id = $category_id;

    return $this;
  }

  /**
   * Gets category_name.
   */
  public function getCategoryName(): ?string
  {
    return $this->category_name;
  }

  /**
   * Sets category_name.
   *
   * @param string|null $category_name Translated category name
   *
   * @return $this
   */
  public function setCategoryName(?string $category_name = null): self
  {
    $this->category_name = $category_name;

    return $this;
  }

  /**
   * Gets flavors.
   *
   * @return string[]|null
   */
  public function getFlavors(): ?array
  {
    return $this->flavors;
  }

  /**
   * Sets flavors.
   *
   * @param string[]|null $flavors
   *
   * @return $this
   */
  public function setFlavors(?array $flavors = null): self
  {
    $this->flavors = $flavors;

    return $this;
  }

  /**
   * Gets download_url.
   */
  public function getDownloadUrl(): ?string
  {
    return $this->download_url;
  }

  /**
   * Sets download_url.
   *
   * @return $this
   */
  public function setDownloadUrl(?string $download_url = null): self
  {
    $this->download_url = $download_url;

    return $this;
  }

  /**
   * Gets thumbnail_url.
   */
  public function getThumbnailUrl(): ?string
  {
    return $this->thumbnail_url;
  }

  /**
   * Sets thumbnail_url.
   *
   * @return $this
   */
  public function setThumbnailUrl(?string $thumbnail_url = null): self
  {
    $this->thumbnail_url = $thumbnail_url;

    return $this;
  }
}
