<?php

/**
 * NotificationsCountResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the NotificationsCountResponse model.
 *
 * @author  OpenAPI Generator team
 */
class NotificationsCountResponse
{
  /**
   * @SerializedName("total")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $total = null;

  /**
   * @SerializedName("like")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $like = null;

  /**
   * @SerializedName("follower")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $follower = null;

  /**
   * @SerializedName("comment")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $comment = null;

  /**
   * @SerializedName("remix")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $remix = null;

  /**
   * @SerializedName("moderation")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $moderation = null;

  /**
   * @SerializedName("studio")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $studio = null;

  /**
   * @SerializedName("project")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $project = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->total = array_key_exists('total', $data) ? $data['total'] : $this->total;
      $this->like = array_key_exists('like', $data) ? $data['like'] : $this->like;
      $this->follower = array_key_exists('follower', $data) ? $data['follower'] : $this->follower;
      $this->comment = array_key_exists('comment', $data) ? $data['comment'] : $this->comment;
      $this->remix = array_key_exists('remix', $data) ? $data['remix'] : $this->remix;
      $this->moderation = array_key_exists('moderation', $data) ? $data['moderation'] : $this->moderation;
      $this->studio = array_key_exists('studio', $data) ? $data['studio'] : $this->studio;
      $this->project = array_key_exists('project', $data) ? $data['project'] : $this->project;
    }
  }

  /**
   * Gets total.
   */
  public function getTotal(): ?int
  {
    return $this->total;
  }

  /**
   * Sets total.
   *
   * @return $this
   */
  public function setTotal(?int $total = null): self
  {
    $this->total = $total;

    return $this;
  }

  /**
   * Gets like.
   */
  public function getLike(): ?int
  {
    return $this->like;
  }

  /**
   * Sets like.
   *
   * @return $this
   */
  public function setLike(?int $like = null): self
  {
    $this->like = $like;

    return $this;
  }

  /**
   * Gets follower.
   */
  public function getFollower(): ?int
  {
    return $this->follower;
  }

  /**
   * Sets follower.
   *
   * @return $this
   */
  public function setFollower(?int $follower = null): self
  {
    $this->follower = $follower;

    return $this;
  }

  /**
   * Gets comment.
   */
  public function getComment(): ?int
  {
    return $this->comment;
  }

  /**
   * Sets comment.
   *
   * @return $this
   */
  public function setComment(?int $comment = null): self
  {
    $this->comment = $comment;

    return $this;
  }

  /**
   * Gets remix.
   */
  public function getRemix(): ?int
  {
    return $this->remix;
  }

  /**
   * Sets remix.
   *
   * @return $this
   */
  public function setRemix(?int $remix = null): self
  {
    $this->remix = $remix;

    return $this;
  }

  /**
   * Gets moderation.
   */
  public function getModeration(): ?int
  {
    return $this->moderation;
  }

  /**
   * Sets moderation.
   *
   * @return $this
   */
  public function setModeration(?int $moderation = null): self
  {
    $this->moderation = $moderation;

    return $this;
  }

  /**
   * Gets studio.
   */
  public function getStudio(): ?int
  {
    return $this->studio;
  }

  /**
   * Sets studio.
   *
   * @return $this
   */
  public function setStudio(?int $studio = null): self
  {
    $this->studio = $studio;

    return $this;
  }

  /**
   * Gets project.
   */
  public function getProject(): ?int
  {
    return $this->project;
  }

  /**
   * Sets project.
   *
   * @return $this
   */
  public function setProject(?int $project = null): self
  {
    $this->project = $project;

    return $this;
  }
}
