<?php

/**
 * ProjectsCategoryListResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the ProjectsCategoryListResponse model.
 *
 * @author  OpenAPI Generator team
 */
class ProjectsCategoryListResponse
{
  /**
   * @var ProjectsCategory[]|null
   *
   * @SerializedName("data")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\ProjectsCategory")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\ProjectsCategory>")
   */
  protected ?array $data = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->data = array_key_exists('data', $data) ? $data['data'] : $this->data;
    }
  }

  /**
   * Gets data.
   *
   * @return ProjectsCategory[]|null
   */
  public function getData(): ?array
  {
    return $this->data;
  }

  /**
   * Sets data.
   *
   * @param ProjectsCategory[]|null $data
   *
   * @return $this
   */
  public function setData(?array $data = null): self
  {
    $this->data = $data;

    return $this;
  }
}
