<?php

/**
 * RemixGraphEdge.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the RemixGraphEdge model.
 *
 * @author  OpenAPI Generator team
 */
class RemixGraphEdge
{
  /**
   * Unique edge id.
   *
   * @SerializedName("id")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * Source node id.
   *
   * @SerializedName("from")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $from = null;

  /**
   * Target node id.
   *
   * @SerializedName("to")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $to = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->from = array_key_exists('from', $data) ? $data['from'] : $this->from;
      $this->to = array_key_exists('to', $data) ? $data['to'] : $this->to;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Unique edge id
   *
   * @return $this
   */
  public function setId(?string $id): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets from.
   */
  public function getFrom(): ?string
  {
    return $this->from;
  }

  /**
   * Sets from.
   *
   * @param string|null $from Source node id
   *
   * @return $this
   */
  public function setFrom(?string $from): self
  {
    $this->from = $from;

    return $this;
  }

  /**
   * Gets to.
   */
  public function getTo(): ?string
  {
    return $this->to;
  }

  /**
   * Sets to.
   *
   * @param string|null $to Target node id
   *
   * @return $this
   */
  public function setTo(?string $to): self
  {
    $this->to = $to;

    return $this;
  }
}
