<?php

/**
 * RemixGraphNode.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the RemixGraphNode model.
 *
 * @author  OpenAPI Generator team
 */
class RemixGraphNode
{
  /**
   * Graph node id composed of source and project id.
   *
   * @SerializedName("id")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * Project ID in its source namespace.
   *
   * @SerializedName("projectId")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $project_id = null;

  /**
   * Source platform of the node.
   *
   * @SerializedName("source")
   *
   * @Assert\NotNull()
   *
   * @Assert\Choice({ "catrobat", "scratch" })
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $source = null;

  /**
   * Whether project metadata is available on the server.
   *
   * @SerializedName("available")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $available = null;

  /**
   * Project title, if available.
   *
   * @SerializedName("name")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $name = null;

  /**
   * Username of the project owner, if available.
   *
   * @SerializedName("username")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $username = null;

  /**
   * Thumbnail URL resolved from project source and availability.
   *
   * @SerializedName("thumbnailUrl")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $thumbnail_url = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->project_id = array_key_exists('project_id', $data) ? $data['project_id'] : $this->project_id;
      $this->source = array_key_exists('source', $data) ? $data['source'] : $this->source;
      $this->available = array_key_exists('available', $data) ? $data['available'] : $this->available;
      $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
      $this->username = array_key_exists('username', $data) ? $data['username'] : $this->username;
      $this->thumbnail_url = array_key_exists('thumbnail_url', $data) ? $data['thumbnail_url'] : $this->thumbnail_url;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Graph node id composed of source and project id
   *
   * @return $this
   */
  public function setId(?string $id): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets project_id.
   */
  public function getProjectId(): ?string
  {
    return $this->project_id;
  }

  /**
   * Sets project_id.
   *
   * @param string|null $project_id Project ID in its source namespace
   *
   * @return $this
   */
  public function setProjectId(?string $project_id): self
  {
    $this->project_id = $project_id;

    return $this;
  }

  /**
   * Gets source.
   */
  public function getSource(): ?string
  {
    return $this->source;
  }

  /**
   * Sets source.
   *
   * @param string|null $source Source platform of the node
   *
   * @return $this
   */
  public function setSource(?string $source): self
  {
    $this->source = $source;

    return $this;
  }

  /**
   * Gets available.
   */
  public function isAvailable(): ?bool
  {
    return $this->available;
  }

  /**
   * Sets available.
   *
   * @param bool|null $available Whether project metadata is available on the server
   *
   * @return $this
   */
  public function setAvailable(?bool $available): self
  {
    $this->available = $available;

    return $this;
  }

  /**
   * Gets name.
   */
  public function getName(): ?string
  {
    return $this->name;
  }

  /**
   * Sets name.
   *
   * @param string|null $name Project title, if available
   *
   * @return $this
   */
  public function setName(?string $name): self
  {
    $this->name = $name;

    return $this;
  }

  /**
   * Gets username.
   */
  public function getUsername(): ?string
  {
    return $this->username;
  }

  /**
   * Sets username.
   *
   * @param string|null $username Username of the project owner, if available
   *
   * @return $this
   */
  public function setUsername(?string $username): self
  {
    $this->username = $username;

    return $this;
  }

  /**
   * Gets thumbnail_url.
   */
  public function getThumbnailUrl(): ?string
  {
    return $this->thumbnail_url;
  }

  /**
   * Sets thumbnail_url.
   *
   * @param string|null $thumbnail_url Thumbnail URL resolved from project source and availability
   *
   * @return $this
   */
  public function setThumbnailUrl(?string $thumbnail_url): self
  {
    $this->thumbnail_url = $thumbnail_url;

    return $this;
  }
}
