<?php

/**
 * ReportReceiptResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the ReportReceiptResponse model.
 *
 * @author  OpenAPI Generator team
 */
class ReportReceiptResponse
{
  /**
   * The unique identifier of the created report.
   *
   * @SerializedName("report_id")
   *
   * @Assert\NotNull()
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $report_id = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->report_id = array_key_exists('report_id', $data) ? $data['report_id'] : $this->report_id;
    }
  }

  /**
   * Gets report_id.
   */
  public function getReportId(): ?string
  {
    return $this->report_id;
  }

  /**
   * Sets report_id.
   *
   * @param string|null $report_id The unique identifier of the created report
   *
   * @return $this
   */
  public function setReportId(?string $report_id): self
  {
    $this->report_id = $report_id;

    return $this;
  }
}
