<?php

/**
 * ResetPasswordRequest.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the ResetPasswordRequest model.
 *
 * @author  OpenAPI Generator team
 */
class ResetPasswordRequest
{
  /**
   * Email of the user.
   *
   * @SerializedName("email")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $email = null;

  /**
   * CAPTCHA response token for bot detection.
   *
   * @SerializedName("captcha_token")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $captcha_token = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->email = array_key_exists('email', $data) ? $data['email'] : $this->email;
      $this->captcha_token = array_key_exists('captcha_token', $data) ? $data['captcha_token'] : $this->captcha_token;
    }
  }

  /**
   * Gets email.
   */
  public function getEmail(): ?string
  {
    return $this->email;
  }

  /**
   * Sets email.
   *
   * @param string|null $email Email of the user
   *
   * @return $this
   */
  public function setEmail(?string $email = null): self
  {
    $this->email = $email;

    return $this;
  }

  /**
   * Gets captcha_token.
   */
  public function getCaptchaToken(): ?string
  {
    return $this->captcha_token;
  }

  /**
   * Sets captcha_token.
   *
   * @param string|null $captcha_token CAPTCHA response token for bot detection
   *
   * @return $this
   */
  public function setCaptchaToken(?string $captcha_token = null): self
  {
    $this->captcha_token = $captcha_token;

    return $this;
  }
}
