<?php

/**
 * SearchResponseStudiosInner.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the SearchResponseStudiosInner model.
 *
 * @author  OpenAPI Generator team
 */
class SearchResponseStudiosInner
{
  /**
   * Studio UUID.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * @SerializedName("name")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $name = null;

  /**
   * @SerializedName("description")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $description = null;

  /**
   * @SerializedName("cover")
   *
   * @Assert\Type("OpenAPI\Server\Model\ImageVariants")
   *
   * @Type("OpenAPI\Server\Model\ImageVariants")
   */
  protected ?ImageVariants $cover = null;

  /**
   * @SerializedName("members_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $members_count = null;

  /**
   * @SerializedName("projects_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $projects_count = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
      $this->description = array_key_exists('description', $data) ? $data['description'] : $this->description;
      $this->cover = array_key_exists('cover', $data) ? $data['cover'] : $this->cover;
      $this->members_count = array_key_exists('members_count', $data) ? $data['members_count'] : $this->members_count;
      $this->projects_count = array_key_exists('projects_count', $data) ? $data['projects_count'] : $this->projects_count;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Studio UUID
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets name.
   */
  public function getName(): ?string
  {
    return $this->name;
  }

  /**
   * Sets name.
   *
   * @return $this
   */
  public function setName(?string $name = null): self
  {
    $this->name = $name;

    return $this;
  }

  /**
   * Gets description.
   */
  public function getDescription(): ?string
  {
    return $this->description;
  }

  /**
   * Sets description.
   *
   * @return $this
   */
  public function setDescription(?string $description = null): self
  {
    $this->description = $description;

    return $this;
  }

  /**
   * Gets cover.
   */
  public function getCover(): ?ImageVariants
  {
    return $this->cover;
  }

  /**
   * Sets cover.
   *
   * @return $this
   */
  public function setCover(?ImageVariants $cover = null): self
  {
    $this->cover = $cover;

    return $this;
  }

  /**
   * Gets members_count.
   */
  public function getMembersCount(): ?int
  {
    return $this->members_count;
  }

  /**
   * Sets members_count.
   *
   * @return $this
   */
  public function setMembersCount(?int $members_count = null): self
  {
    $this->members_count = $members_count;

    return $this;
  }

  /**
   * Gets projects_count.
   */
  public function getProjectsCount(): ?int
  {
    return $this->projects_count;
  }

  /**
   * Sets projects_count.
   *
   * @return $this
   */
  public function setProjectsCount(?int $projects_count = null): self
  {
    $this->projects_count = $projects_count;

    return $this;
  }
}
