<?php

/**
 * StudioJoinRequestListResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the StudioJoinRequestListResponse model.
 *
 * @author  OpenAPI Generator team
 */
class StudioJoinRequestListResponse
{
  /**
   * @var StudioJoinRequestResponse[]|null
   *
   * @SerializedName("data")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\StudioJoinRequestResponse")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\StudioJoinRequestResponse>")
   */
  protected ?array $data = null;

  /**
   * @SerializedName("has_more")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $has_more = null;

  /**
   * @SerializedName("next_cursor")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $next_cursor = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->data = array_key_exists('data', $data) ? $data['data'] : $this->data;
      $this->has_more = array_key_exists('has_more', $data) ? $data['has_more'] : $this->has_more;
      $this->next_cursor = array_key_exists('next_cursor', $data) ? $data['next_cursor'] : $this->next_cursor;
    }
  }

  /**
   * Gets data.
   *
   * @return StudioJoinRequestResponse[]|null
   */
  public function getData(): ?array
  {
    return $this->data;
  }

  /**
   * Sets data.
   *
   * @param StudioJoinRequestResponse[]|null $data
   *
   * @return $this
   */
  public function setData(?array $data = null): self
  {
    $this->data = $data;

    return $this;
  }

  /**
   * Gets has_more.
   */
  public function isHasMore(): ?bool
  {
    return $this->has_more;
  }

  /**
   * Sets has_more.
   *
   * @return $this
   */
  public function setHasMore(?bool $has_more = null): self
  {
    $this->has_more = $has_more;

    return $this;
  }

  /**
   * Gets next_cursor.
   */
  public function getNextCursor(): ?string
  {
    return $this->next_cursor;
  }

  /**
   * Sets next_cursor.
   *
   * @return $this
   */
  public function setNextCursor(?string $next_cursor = null): self
  {
    $this->next_cursor = $next_cursor;

    return $this;
  }
}
