<?php

/**
 * StudioCommentResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the StudioCommentResponse model.
 *
 * @author  OpenAPI Generator team
 */
class StudioCommentResponse
{
  /**
   * Comment UUID.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * @SerializedName("message")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $message = null;

  /**
   * @SerializedName("username")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $username = null;

  /**
   * @SerializedName("user_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $user_id = null;

  /**
   * @SerializedName("user_avatar")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $user_avatar = null;

  /**
   * @SerializedName("parent_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $parent_id = null;

  /**
   * @SerializedName("reply_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $reply_count = null;

  /**
   * @SerializedName("created_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $created_at = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->message = array_key_exists('message', $data) ? $data['message'] : $this->message;
      $this->username = array_key_exists('username', $data) ? $data['username'] : $this->username;
      $this->user_id = array_key_exists('user_id', $data) ? $data['user_id'] : $this->user_id;
      $this->user_avatar = array_key_exists('user_avatar', $data) ? $data['user_avatar'] : $this->user_avatar;
      $this->parent_id = array_key_exists('parent_id', $data) ? $data['parent_id'] : $this->parent_id;
      $this->reply_count = array_key_exists('reply_count', $data) ? $data['reply_count'] : $this->reply_count;
      $this->created_at = array_key_exists('created_at', $data) ? $data['created_at'] : $this->created_at;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Comment UUID
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets message.
   */
  public function getMessage(): ?string
  {
    return $this->message;
  }

  /**
   * Sets message.
   *
   * @return $this
   */
  public function setMessage(?string $message = null): self
  {
    $this->message = $message;

    return $this;
  }

  /**
   * Gets username.
   */
  public function getUsername(): ?string
  {
    return $this->username;
  }

  /**
   * Sets username.
   *
   * @return $this
   */
  public function setUsername(?string $username = null): self
  {
    $this->username = $username;

    return $this;
  }

  /**
   * Gets user_id.
   */
  public function getUserId(): ?string
  {
    return $this->user_id;
  }

  /**
   * Sets user_id.
   *
   * @return $this
   */
  public function setUserId(?string $user_id = null): self
  {
    $this->user_id = $user_id;

    return $this;
  }

  /**
   * Gets user_avatar.
   */
  public function getUserAvatar(): ?string
  {
    return $this->user_avatar;
  }

  /**
   * Sets user_avatar.
   *
   * @return $this
   */
  public function setUserAvatar(?string $user_avatar = null): self
  {
    $this->user_avatar = $user_avatar;

    return $this;
  }

  /**
   * Gets parent_id.
   */
  public function getParentId(): ?string
  {
    return $this->parent_id;
  }

  /**
   * Sets parent_id.
   *
   * @return $this
   */
  public function setParentId(?string $parent_id = null): self
  {
    $this->parent_id = $parent_id;

    return $this;
  }

  /**
   * Gets reply_count.
   */
  public function getReplyCount(): ?int
  {
    return $this->reply_count;
  }

  /**
   * Sets reply_count.
   *
   * @return $this
   */
  public function setReplyCount(?int $reply_count = null): self
  {
    $this->reply_count = $reply_count;

    return $this;
  }

  /**
   * Gets created_at.
   */
  public function getCreatedAt(): ?\DateTime
  {
    return $this->created_at;
  }

  /**
   * Sets created_at.
   *
   * @return $this
   */
  public function setCreatedAt(?\DateTime $created_at = null): self
  {
    $this->created_at = $created_at;

    return $this;
  }
}
