<?php

/**
 * StudioMemberResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the StudioMemberResponse model.
 *
 * @author  OpenAPI Generator team
 */
class StudioMemberResponse
{
  /**
   * Studio membership UUID.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * User UUID.
   *
   * @SerializedName("user_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $user_id = null;

  /**
   * @SerializedName("username")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $username = null;

  /**
   * @SerializedName("avatar")
   *
   * @Assert\Type("OpenAPI\Server\Model\ImageVariants")
   *
   * @Type("OpenAPI\Server\Model\ImageVariants")
   */
  protected ?ImageVariants $avatar = null;

  /**
   * @SerializedName("role")
   *
   * @Assert\Choice({ "admin", "member" })
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $role = null;

  /**
   * @SerializedName("status")
   *
   * @Assert\Choice({ "active", "banned", "pending_request" })
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $status = null;

  /**
   * @SerializedName("joined_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $joined_at = null;

  /**
   * Number of projects this member has in the studio.
   *
   * @SerializedName("studio_project_count")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $studio_project_count = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->user_id = array_key_exists('user_id', $data) ? $data['user_id'] : $this->user_id;
      $this->username = array_key_exists('username', $data) ? $data['username'] : $this->username;
      $this->avatar = array_key_exists('avatar', $data) ? $data['avatar'] : $this->avatar;
      $this->role = array_key_exists('role', $data) ? $data['role'] : $this->role;
      $this->status = array_key_exists('status', $data) ? $data['status'] : $this->status;
      $this->joined_at = array_key_exists('joined_at', $data) ? $data['joined_at'] : $this->joined_at;
      $this->studio_project_count = array_key_exists('studio_project_count', $data) ? $data['studio_project_count'] : $this->studio_project_count;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Studio membership UUID
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets user_id.
   */
  public function getUserId(): ?string
  {
    return $this->user_id;
  }

  /**
   * Sets user_id.
   *
   * @param string|null $user_id User UUID
   *
   * @return $this
   */
  public function setUserId(?string $user_id = null): self
  {
    $this->user_id = $user_id;

    return $this;
  }

  /**
   * Gets username.
   */
  public function getUsername(): ?string
  {
    return $this->username;
  }

  /**
   * Sets username.
   *
   * @return $this
   */
  public function setUsername(?string $username = null): self
  {
    $this->username = $username;

    return $this;
  }

  /**
   * Gets avatar.
   */
  public function getAvatar(): ?ImageVariants
  {
    return $this->avatar;
  }

  /**
   * Sets avatar.
   *
   * @return $this
   */
  public function setAvatar(?ImageVariants $avatar = null): self
  {
    $this->avatar = $avatar;

    return $this;
  }

  /**
   * Gets role.
   */
  public function getRole(): ?string
  {
    return $this->role;
  }

  /**
   * Sets role.
   *
   * @return $this
   */
  public function setRole(?string $role = null): self
  {
    $this->role = $role;

    return $this;
  }

  /**
   * Gets status.
   */
  public function getStatus(): ?string
  {
    return $this->status;
  }

  /**
   * Sets status.
   *
   * @return $this
   */
  public function setStatus(?string $status = null): self
  {
    $this->status = $status;

    return $this;
  }

  /**
   * Gets joined_at.
   */
  public function getJoinedAt(): ?\DateTime
  {
    return $this->joined_at;
  }

  /**
   * Sets joined_at.
   *
   * @return $this
   */
  public function setJoinedAt(?\DateTime $joined_at = null): self
  {
    $this->joined_at = $joined_at;

    return $this;
  }

  /**
   * Gets studio_project_count.
   */
  public function getStudioProjectCount(): ?int
  {
    return $this->studio_project_count;
  }

  /**
   * Sets studio_project_count.
   *
   * @param int|null $studio_project_count Number of projects this member has in the studio
   *
   * @return $this
   */
  public function setStudioProjectCount(?int $studio_project_count = null): self
  {
    $this->studio_project_count = $studio_project_count;

    return $this;
  }
}
