<?php

/**
 * StudioJoinRequestResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the StudioJoinRequestResponse model.
 *
 * @author  OpenAPI Generator team
 */
class StudioJoinRequestResponse
{
  /**
   * Join request UUID.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * User UUID.
   *
   * @SerializedName("user_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $user_id = null;

  /**
   * @SerializedName("username")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $username = null;

  /**
   * @SerializedName("avatar")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $avatar = null;

  /**
   * @SerializedName("status")
   *
   * @Assert\Choice({ "pending", "approved", "declined" })
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $status = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->user_id = array_key_exists('user_id', $data) ? $data['user_id'] : $this->user_id;
      $this->username = array_key_exists('username', $data) ? $data['username'] : $this->username;
      $this->avatar = array_key_exists('avatar', $data) ? $data['avatar'] : $this->avatar;
      $this->status = array_key_exists('status', $data) ? $data['status'] : $this->status;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Join request UUID
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets user_id.
   */
  public function getUserId(): ?string
  {
    return $this->user_id;
  }

  /**
   * Sets user_id.
   *
   * @param string|null $user_id User UUID
   *
   * @return $this
   */
  public function setUserId(?string $user_id = null): self
  {
    $this->user_id = $user_id;

    return $this;
  }

  /**
   * Gets username.
   */
  public function getUsername(): ?string
  {
    return $this->username;
  }

  /**
   * Sets username.
   *
   * @return $this
   */
  public function setUsername(?string $username = null): self
  {
    $this->username = $username;

    return $this;
  }

  /**
   * Gets avatar.
   */
  public function getAvatar(): ?string
  {
    return $this->avatar;
  }

  /**
   * Sets avatar.
   *
   * @return $this
   */
  public function setAvatar(?string $avatar = null): self
  {
    $this->avatar = $avatar;

    return $this;
  }

  /**
   * Gets status.
   */
  public function getStatus(): ?string
  {
    return $this->status;
  }

  /**
   * Sets status.
   *
   * @return $this
   */
  public function setStatus(?string $status = null): self
  {
    $this->status = $status;

    return $this;
  }
}
