<?php

/**
 * StudioProjectResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the StudioProjectResponse model.
 *
 * @author  OpenAPI Generator team
 */
class StudioProjectResponse
{
  /**
   * Project UUID.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * @SerializedName("name")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $name = null;

  /**
   * Username of the user who added the project.
   *
   * @SerializedName("added_by")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $added_by = null;

  /**
   * @SerializedName("added_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $added_at = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
      $this->added_by = array_key_exists('added_by', $data) ? $data['added_by'] : $this->added_by;
      $this->added_at = array_key_exists('added_at', $data) ? $data['added_at'] : $this->added_at;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Project UUID
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets name.
   */
  public function getName(): ?string
  {
    return $this->name;
  }

  /**
   * Sets name.
   *
   * @return $this
   */
  public function setName(?string $name = null): self
  {
    $this->name = $name;

    return $this;
  }

  /**
   * Gets added_by.
   */
  public function getAddedBy(): ?string
  {
    return $this->added_by;
  }

  /**
   * Sets added_by.
   *
   * @param string|null $added_by Username of the user who added the project
   *
   * @return $this
   */
  public function setAddedBy(?string $added_by = null): self
  {
    $this->added_by = $added_by;

    return $this;
  }

  /**
   * Gets added_at.
   */
  public function getAddedAt(): ?\DateTime
  {
    return $this->added_at;
  }

  /**
   * Sets added_at.
   *
   * @return $this
   */
  public function setAddedAt(?\DateTime $added_at = null): self
  {
    $this->added_at = $added_at;

    return $this;
  }
}
