<?php

/**
 * StudioProjectResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the StudioProjectResponse model.
 *
 * @author  OpenAPI Generator team
 */
class StudioProjectResponse
{
  /**
   * Project UUID.
   *
   * @SerializedName("id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $id = null;

  /**
   * @SerializedName("name")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $name = null;

  /**
   * Username of the user who added the project.
   *
   * @SerializedName("added_by")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $added_by = null;

  /**
   * @SerializedName("added_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $added_at = null;

  /**
   * Path to the project thumbnail.
   *
   * @SerializedName("screenshot_small")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $screenshot_small = null;

  /**
   * Username of the project author.
   *
   * @SerializedName("author")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $author = null;

  /**
   * UUID of the project author.
   *
   * @SerializedName("author_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $author_id = null;

  /**
   * Download count.
   *
   * @SerializedName("downloads")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $downloads = null;

  /**
   * View count.
   *
   * @SerializedName("views")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $views = null;

  /**
   * Localized upload time.
   *
   * @SerializedName("uploaded_string")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $uploaded_string = null;

  /**
   * Whether the project is private.
   *
   * @SerializedName("private")
   *
   * @Assert\Type("bool")
   *
   * @Type("bool")
   */
  protected ?bool $private = null;

  /**
   * Not-for-kids flag (0&#x3D;safe, 1&#x3D;flagged, 2&#x3D;moderator-flagged).
   *
   * @SerializedName("not_for_kids")
   *
   * @Assert\Type("int")
   *
   * @Type("int")
   */
  protected ?int $not_for_kids = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
      $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
      $this->added_by = array_key_exists('added_by', $data) ? $data['added_by'] : $this->added_by;
      $this->added_at = array_key_exists('added_at', $data) ? $data['added_at'] : $this->added_at;
      $this->screenshot_small = array_key_exists('screenshot_small', $data) ? $data['screenshot_small'] : $this->screenshot_small;
      $this->author = array_key_exists('author', $data) ? $data['author'] : $this->author;
      $this->author_id = array_key_exists('author_id', $data) ? $data['author_id'] : $this->author_id;
      $this->downloads = array_key_exists('downloads', $data) ? $data['downloads'] : $this->downloads;
      $this->views = array_key_exists('views', $data) ? $data['views'] : $this->views;
      $this->uploaded_string = array_key_exists('uploaded_string', $data) ? $data['uploaded_string'] : $this->uploaded_string;
      $this->private = array_key_exists('private', $data) ? $data['private'] : $this->private;
      $this->not_for_kids = array_key_exists('not_for_kids', $data) ? $data['not_for_kids'] : $this->not_for_kids;
    }
  }

  /**
   * Gets id.
   */
  public function getId(): ?string
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param string|null $id Project UUID
   *
   * @return $this
   */
  public function setId(?string $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets name.
   */
  public function getName(): ?string
  {
    return $this->name;
  }

  /**
   * Sets name.
   *
   * @return $this
   */
  public function setName(?string $name = null): self
  {
    $this->name = $name;

    return $this;
  }

  /**
   * Gets added_by.
   */
  public function getAddedBy(): ?string
  {
    return $this->added_by;
  }

  /**
   * Sets added_by.
   *
   * @param string|null $added_by Username of the user who added the project
   *
   * @return $this
   */
  public function setAddedBy(?string $added_by = null): self
  {
    $this->added_by = $added_by;

    return $this;
  }

  /**
   * Gets added_at.
   */
  public function getAddedAt(): ?\DateTime
  {
    return $this->added_at;
  }

  /**
   * Sets added_at.
   *
   * @return $this
   */
  public function setAddedAt(?\DateTime $added_at = null): self
  {
    $this->added_at = $added_at;

    return $this;
  }

  /**
   * Gets screenshot_small.
   */
  public function getScreenshotSmall(): ?string
  {
    return $this->screenshot_small;
  }

  /**
   * Sets screenshot_small.
   *
   * @param string|null $screenshot_small Path to the project thumbnail
   *
   * @return $this
   */
  public function setScreenshotSmall(?string $screenshot_small = null): self
  {
    $this->screenshot_small = $screenshot_small;

    return $this;
  }

  /**
   * Gets author.
   */
  public function getAuthor(): ?string
  {
    return $this->author;
  }

  /**
   * Sets author.
   *
   * @param string|null $author Username of the project author
   *
   * @return $this
   */
  public function setAuthor(?string $author = null): self
  {
    $this->author = $author;

    return $this;
  }

  /**
   * Gets author_id.
   */
  public function getAuthorId(): ?string
  {
    return $this->author_id;
  }

  /**
   * Sets author_id.
   *
   * @param string|null $author_id UUID of the project author
   *
   * @return $this
   */
  public function setAuthorId(?string $author_id = null): self
  {
    $this->author_id = $author_id;

    return $this;
  }

  /**
   * Gets downloads.
   */
  public function getDownloads(): ?int
  {
    return $this->downloads;
  }

  /**
   * Sets downloads.
   *
   * @param int|null $downloads Download count
   *
   * @return $this
   */
  public function setDownloads(?int $downloads = null): self
  {
    $this->downloads = $downloads;

    return $this;
  }

  /**
   * Gets views.
   */
  public function getViews(): ?int
  {
    return $this->views;
  }

  /**
   * Sets views.
   *
   * @param int|null $views View count
   *
   * @return $this
   */
  public function setViews(?int $views = null): self
  {
    $this->views = $views;

    return $this;
  }

  /**
   * Gets uploaded_string.
   */
  public function getUploadedString(): ?string
  {
    return $this->uploaded_string;
  }

  /**
   * Sets uploaded_string.
   *
   * @param string|null $uploaded_string Localized upload time
   *
   * @return $this
   */
  public function setUploadedString(?string $uploaded_string = null): self
  {
    $this->uploaded_string = $uploaded_string;

    return $this;
  }

  /**
   * Gets private.
   */
  public function isPrivate(): ?bool
  {
    return $this->private;
  }

  /**
   * Sets private.
   *
   * @param bool|null $private Whether the project is private
   *
   * @return $this
   */
  public function setPrivate(?bool $private = null): self
  {
    $this->private = $private;

    return $this;
  }

  /**
   * Gets not_for_kids.
   */
  public function getNotForKids(): ?int
  {
    return $this->not_for_kids;
  }

  /**
   * Sets not_for_kids.
   *
   * @param int|null $not_for_kids Not-for-kids flag (0=safe, 1=flagged, 2=moderator-flagged)
   *
   * @return $this
   */
  public function setNotForKids(?int $not_for_kids = null): self
  {
    $this->not_for_kids = $not_for_kids;

    return $this;
  }
}
