<?php

/**
 * UserDataExportResponseReactionsInner.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the UserDataExportResponseReactionsInner model.
 *
 * @author  OpenAPI Generator team
 */
class UserDataExportResponseReactionsInner
{
  /**
   * @SerializedName("project_id")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $project_id = null;

  /**
   * @SerializedName("type")
   *
   * @Assert\Type("string")
   *
   * @Type("string")
   */
  protected ?string $type = null;

  /**
   * @SerializedName("created_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $created_at = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->project_id = array_key_exists('project_id', $data) ? $data['project_id'] : $this->project_id;
      $this->type = array_key_exists('type', $data) ? $data['type'] : $this->type;
      $this->created_at = array_key_exists('created_at', $data) ? $data['created_at'] : $this->created_at;
    }
  }

  /**
   * Gets project_id.
   */
  public function getProjectId(): ?string
  {
    return $this->project_id;
  }

  /**
   * Sets project_id.
   *
   * @return $this
   */
  public function setProjectId(?string $project_id = null): self
  {
    $this->project_id = $project_id;

    return $this;
  }

  /**
   * Gets type.
   */
  public function getType(): ?string
  {
    return $this->type;
  }

  /**
   * Sets type.
   *
   * @return $this
   */
  public function setType(?string $type = null): self
  {
    $this->type = $type;

    return $this;
  }

  /**
   * Gets created_at.
   */
  public function getCreatedAt(): ?\DateTime
  {
    return $this->created_at;
  }

  /**
   * Sets created_at.
   *
   * @return $this
   */
  public function setCreatedAt(?\DateTime $created_at = null): self
  {
    $this->created_at = $created_at;

    return $this;
  }
}
