<?php

/**
 * UserDataExportResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.6.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the UserDataExportResponse model.
 *
 * Full personal data export for GDPR data portability
 *
 * @author  OpenAPI Generator team
 */
class UserDataExportResponse
{
  /**
   * Timestamp when the export was generated.
   *
   * @SerializedName("exported_at")
   *
   * @Assert\Type("\DateTime"))
   *
   * @Type("DateTime")
   */
  protected ?\DateTime $exported_at = null;

  /**
   * @SerializedName("profile")
   *
   * @Assert\Type("OpenAPI\Server\Model\UserDataExportResponseProfile")
   *
   * @Type("OpenAPI\Server\Model\UserDataExportResponseProfile")
   */
  protected ?UserDataExportResponseProfile $profile = null;

  /**
   * Projects uploaded by the user.
   *
   * @var UserDataExportResponseProjectsInner[]|null
   *
   * @SerializedName("projects")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\UserDataExportResponseProjectsInner")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\UserDataExportResponseProjectsInner>")
   */
  protected ?array $projects = null;

  /**
   * Comments written by the user.
   *
   * @var UserDataExportResponseCommentsInner[]|null
   *
   * @SerializedName("comments")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\UserDataExportResponseCommentsInner")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\UserDataExportResponseCommentsInner>")
   */
  protected ?array $comments = null;

  /**
   * Reactions (likes) given by the user.
   *
   * @var UserDataExportResponseReactionsInner[]|null
   *
   * @SerializedName("reactions")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\UserDataExportResponseReactionsInner")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\UserDataExportResponseReactionsInner>")
   */
  protected ?array $reactions = null;

  /**
   * Users who follow this user.
   *
   * @var UserDataExportResponseFollowersInner[]|null
   *
   * @SerializedName("followers")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\UserDataExportResponseFollowersInner")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\UserDataExportResponseFollowersInner>")
   */
  protected ?array $followers = null;

  /**
   * Users followed by this user.
   *
   * @var UserDataExportResponseFollowersInner[]|null
   *
   * @SerializedName("following")
   *
   * @Assert\All({
   *
   *   @Assert\Type("OpenAPI\Server\Model\UserDataExportResponseFollowersInner")
   * })
   *
   * @Type("array<OpenAPI\Server\Model\UserDataExportResponseFollowersInner>")
   */
  protected ?array $following = null;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(?array $data = null)
  {
    if (is_array($data)) {
      $this->exported_at = array_key_exists('exported_at', $data) ? $data['exported_at'] : $this->exported_at;
      $this->profile = array_key_exists('profile', $data) ? $data['profile'] : $this->profile;
      $this->projects = array_key_exists('projects', $data) ? $data['projects'] : $this->projects;
      $this->comments = array_key_exists('comments', $data) ? $data['comments'] : $this->comments;
      $this->reactions = array_key_exists('reactions', $data) ? $data['reactions'] : $this->reactions;
      $this->followers = array_key_exists('followers', $data) ? $data['followers'] : $this->followers;
      $this->following = array_key_exists('following', $data) ? $data['following'] : $this->following;
    }
  }

  /**
   * Gets exported_at.
   */
  public function getExportedAt(): ?\DateTime
  {
    return $this->exported_at;
  }

  /**
   * Sets exported_at.
   *
   * @param \DateTime|null $exported_at Timestamp when the export was generated
   *
   * @return $this
   */
  public function setExportedAt(?\DateTime $exported_at = null): self
  {
    $this->exported_at = $exported_at;

    return $this;
  }

  /**
   * Gets profile.
   */
  public function getProfile(): ?UserDataExportResponseProfile
  {
    return $this->profile;
  }

  /**
   * Sets profile.
   *
   * @return $this
   */
  public function setProfile(?UserDataExportResponseProfile $profile = null): self
  {
    $this->profile = $profile;

    return $this;
  }

  /**
   * Gets projects.
   *
   * @return UserDataExportResponseProjectsInner[]|null
   */
  public function getProjects(): ?array
  {
    return $this->projects;
  }

  /**
   * Sets projects.
   *
   * @param UserDataExportResponseProjectsInner[]|null $projects Projects uploaded by the user
   *
   * @return $this
   */
  public function setProjects(?array $projects = null): self
  {
    $this->projects = $projects;

    return $this;
  }

  /**
   * Gets comments.
   *
   * @return UserDataExportResponseCommentsInner[]|null
   */
  public function getComments(): ?array
  {
    return $this->comments;
  }

  /**
   * Sets comments.
   *
   * @param UserDataExportResponseCommentsInner[]|null $comments Comments written by the user
   *
   * @return $this
   */
  public function setComments(?array $comments = null): self
  {
    $this->comments = $comments;

    return $this;
  }

  /**
   * Gets reactions.
   *
   * @return UserDataExportResponseReactionsInner[]|null
   */
  public function getReactions(): ?array
  {
    return $this->reactions;
  }

  /**
   * Sets reactions.
   *
   * @param UserDataExportResponseReactionsInner[]|null $reactions Reactions (likes) given by the user
   *
   * @return $this
   */
  public function setReactions(?array $reactions = null): self
  {
    $this->reactions = $reactions;

    return $this;
  }

  /**
   * Gets followers.
   *
   * @return UserDataExportResponseFollowersInner[]|null
   */
  public function getFollowers(): ?array
  {
    return $this->followers;
  }

  /**
   * Sets followers.
   *
   * @param UserDataExportResponseFollowersInner[]|null $followers Users who follow this user
   *
   * @return $this
   */
  public function setFollowers(?array $followers = null): self
  {
    $this->followers = $followers;

    return $this;
  }

  /**
   * Gets following.
   *
   * @return UserDataExportResponseFollowersInner[]|null
   */
  public function getFollowing(): ?array
  {
    return $this->following;
  }

  /**
   * Sets following.
   *
   * @param UserDataExportResponseFollowersInner[]|null $following Users followed by this user
   *
   * @return $this
   */
  public function setFollowing(?array $following = null): self
  {
    $this->following = $following;

    return $this;
  }
}
