#
# Possible Error levels:
#    DEBUG:     Detailed debug information.
#    INFO:      Interesting events. Examples: User logs in, SQL logs.
#    NOTICE:    Normal but significant events.
#    WARNING:   Exceptional occurrences that are not errors.
#               Examples: deprecated APIs, poor use of an API, undesirable things that are not necessarily wrong.
#    ERROR:     Runtime errors that do not require immediate action but should typically be logged and monitored.
#    CRITICAL:  Critical conditions. Example: Application component unavailable, unexpected exception.
#    ALERT:     Action must be taken immediately. Example: Entire website down, database unavailable, etc.
#               This should trigger the SMS alerts and wake you up.
#    EMERGENCY: Emergency: system is unusable.
#
# The fingers crossed type allows us to use a nested handler which logs everything but only
# passes them to a second handler if a minimum error level was reached.
#
# Rotate File can be used to create separate files for every day to prevent too large log files.
#
# FirePhp and ChromePhp allow us to log to the firefox and chrome browser
#

monolog:
  channels: [upload, download_stats]
  handlers:

    firephp:
      type: firephp
      level: info
    chromephp:
      type: chromephp
      level: info

    main:
      type:  fingers_crossed
      action_level: error
      handler: nested
    nested:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
      level: info
      max_files: 5

    upload:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%/upload/upload.log"
      level: debug
      max_files: 5
      channels: [upload]

    download_stats:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%/download_stats/download_stats.log"
      level: debug
      max_files: 5
      channels: [download_stats]

    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]

    deprecation:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.deprecations.log"
    deprecation_filter:
      type: filter
      handler: deprecation
      max_level: info
      channels: ["php"]
