<?php

namespace Catrobat\AppBundle\Entity;

/**
 * CatroNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatroNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
