<?php

namespace Catrobat\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExtensionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtensionRepository extends EntityRepository
{
    public function getAllExtensionsPrefix()
    {
        $qb = $this->createQueryBuilder('e');

        return $qb
            ->select('e.prefix')
            ->getQuery()
            ->getResult();

    }

    public function getExtensionByName($name)
    {
        $qb = $this->createQueryBuilder('e');

        return $qb
            ->select('e')
            ->where($qb->expr()->eq('e.name', ':name'))
            ->setParameter('name', $name)
            ->getQuery()
            ->getResult();
    }
}
