<?php

namespace Catrobat\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
  /**
   * @param $language
   *
   * @return mixed
   */
  public function getConstantTags($language)
  {
    $qb = $this->createQueryBuilder('e');

    return $qb
      ->select('e.' . $language)
      ->getQuery()
      ->getResult();
  }

  /**
   * @param $program_id
   * @param $language
   *
   * @return mixed
   */
  public function getTagsWithProgramIdAndLanguage($program_id, $language)
  {
    $qb = $this->createQueryBuilder('e');

    return $qb
      ->select('e.' . $language)
      ->leftJoin('e.programs', 'p')
      ->andWhere($qb->expr()->eq('p.id', ':id'))
      ->setParameter('id', $program_id)
      ->getQuery()
      ->getResult();
  }
}
