name: 'Install php and composer vendor libraries'
description: 'Install php and composer vendor libraries. Caching is enabled for enhanced performance.'
runs:
  using: 'composite'
  steps:
    - name: 'Setup PHP 8.3'
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: 'Ensure composer configuration is valid'
      shell: bash
      run: composer validate

    - name: 'Use caching action to improve performance'
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: |
          vendor
          bin/behat
          bin/phpunit
          bin/phpstan
          bin/php-cs-fixer
          bin/phpdd
          bin/psalm
          bin/dep
        key: ${{ runner.os }}-php--${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php--

    - name: 'Only install packages if there is no cache hit'
      # "If" not yet supported: https://github.com/actions/runner/issues/834 -> shell workaround
      #      - if: steps.composer-cache.outputs.cache-hit != 'true'
      #        run: composer install --prefer-dist --no-progress
      shell: bash
      run: |
        if echo ${{ steps.composer-cache.outputs.cache-hit }} | grep -c "true"
        then
          echo "Cache hit - skipping dependency installation"
        else
          composer install --prefer-dist --no-progress
        fi
