name: 'Install php and composer vendor libraries'
description: 'Install php and composer vendor libraries. Caching is enabled for enhanced performance.'
runs:
  using: "composite"
  steps:
    - name: "Setup PHP 7.4"
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: "Install dependencies (php-imagick)"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install php-imagick

    - name: "Ensure composer configuration is valid"
      shell: bash
      run: composer validate

    - name: "Use caching action to improve performance"
      id: composer-cache
      uses: actions/cache@v2.1.6
      with:
        path: |
          vendor
          bin/behat
          bin/phpunit
          bin/phpstan
          bin/php-cs-fixer
          bin/phpdd
          bin/psalm
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: "Only install packages if there is no cache hit"
      # "If" not yet supported: https://github.com/actions/runner/issues/834 -> shell workaround
      #      - if: steps.composer-cache.outputs.cache-hit != 'true'
      #        run: composer install --prefer-dist --no-progress
      shell: bash
      run: |
        if echo ${{ steps.composer-cache.outputs.cache-hit }} | grep -c "true"
        then
          echo "Cache hit - skipping dependency installation"
        else
          composer install --prefer-dist --no-progress
        fi