<?php

/**
 * ModerationApiInterface.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use OpenAPI\Server\Model\ContentAppealRequest;
use OpenAPI\Server\Model\ContentReportRequest;
use OpenAPI\Server\Model\ResolveAppealRequest;
use OpenAPI\Server\Model\ResolveReportRequest;

/**
 * ModerationApiInterface Interface Doc Comment.
 *
 * @category Interface
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */
interface ModerationApiInterface
{
  /**
   * Sets authentication method BearerAuth.
   *
   * @param string|null $value value of the BearerAuth authentication method
   */
  public function setBearerAuth(?string $value): void;

  /**
   * Operation commentsIdAppealPost.
   *
   * Appeal a hidden comment
   *
   * @param string               $id                     (required)
   * @param ContentAppealRequest $content_appeal_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function commentsIdAppealPost(
    string $id,
    ContentAppealRequest $content_appeal_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation commentsIdReportPost.
   *
   * Report a comment
   *
   * @param string               $id                     (required)
   * @param ContentReportRequest $content_report_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function commentsIdReportPost(
    string $id,
    ContentReportRequest $content_report_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation moderationAppealsGet.
   *
   * List pending appeals (admin only)
   *
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function moderationAppealsGet(
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation moderationAppealsIdResolvePut.
   *
   * Resolve an appeal (approve or reject, admin only)
   *
   * @param string               $id                     (required)
   * @param ResolveAppealRequest $resolve_appeal_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function moderationAppealsIdResolvePut(
    string $id,
    ResolveAppealRequest $resolve_appeal_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation moderationReportsGet.
   *
   * List pending reports (admin only)
   *
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function moderationReportsGet(
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation moderationReportsIdResolvePut.
   *
   * Resolve a report (accept or reject, admin only)
   *
   * @param string               $id                     (required)
   * @param ResolveReportRequest $resolve_report_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function moderationReportsIdResolvePut(
    string $id,
    ResolveReportRequest $resolve_report_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation projectsIdAppealPost.
   *
   * Appeal a hidden project
   *
   * @param string               $id                     (required)
   * @param ContentAppealRequest $content_appeal_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function projectsIdAppealPost(
    string $id,
    ContentAppealRequest $content_appeal_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation projectsIdReportPost.
   *
   * Report a project
   *
   * @param string               $id                     (required)
   * @param ContentReportRequest $content_report_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function projectsIdReportPost(
    string $id,
    ContentReportRequest $content_report_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdAppealPost.
   *
   * Appeal a hidden studio
   *
   * @param string               $id                     (required)
   * @param ContentAppealRequest $content_appeal_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function studiosIdAppealPost(
    string $id,
    ContentAppealRequest $content_appeal_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdReportPost.
   *
   * Report a studio
   *
   * @param string               $id                     (required)
   * @param ContentReportRequest $content_report_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function studiosIdReportPost(
    string $id,
    ContentReportRequest $content_report_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation usersIdAppealPost.
   *
   * Appeal a hidden user profile
   *
   * @param string               $id                     (required)
   * @param ContentAppealRequest $content_appeal_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function usersIdAppealPost(
    string $id,
    ContentAppealRequest $content_appeal_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation usersIdReportPost.
   *
   * Report a user
   *
   * @param string               $id                     (required)
   * @param ContentReportRequest $content_report_request (required)
   * @param int                  &$responseCode          The HTTP Response Code
   * @param array                $responseHeaders        Additional HTTP headers to return with the response ()
   */
  public function usersIdReportPost(
    string $id,
    ContentReportRequest $content_report_request,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation usersMeReportsGet.
   *
   * List reports filed by the current user
   *
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function usersMeReportsGet(
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;
}
