<?php

/**
 * StudiosApiInterface.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v2.0.0
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use OpenAPI\Server\Model\StudioAddProjectRequest;
use OpenAPI\Server\Model\StudioBatchAddProjectsRequest;
use OpenAPI\Server\Model\StudioCommentCreateRequest;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * StudiosApiInterface Interface Doc Comment.
 *
 * @category Interface
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */
interface StudiosApiInterface
{
  /**
   * Sets authentication method BearerAuth.
   *
   * @param string|null $value value of the BearerAuth authentication method
   */
  public function setBearerAuth(?string $value): void;

  /**
   * Operation studiosGet.
   *
   * List public studios
   *
   * @param string      $accept_language (optional, default to 'en')
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosGet(
    string $accept_language,
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdActivitiesGet.
   *
   * List studio activities
   *
   * @param string      $id              (required)
   * @param string      $accept_language (optional, default to 'en')
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdActivitiesGet(
    string $id,
    string $accept_language,
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdBatchAddProjectsPost.
   *
   * Add multiple projects to a studio in a single request
   *
   * @param string                        $id                                (required)
   * @param StudioBatchAddProjectsRequest $studio_batch_add_projects_request (required)
   * @param string                        $accept_language                   (optional, default to 'en')
   * @param int                           &$responseCode                     The HTTP Response Code
   * @param array                         $responseHeaders                   Additional HTTP headers to return with the response ()
   */
  public function studiosIdBatchAddProjectsPost(
    string $id,
    StudioBatchAddProjectsRequest $studio_batch_add_projects_request,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdCommentsCommentIdDelete.
   *
   * Delete a studio comment
   *
   * @param string $id              (required)
   * @param string $comment_id      (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdCommentsCommentIdDelete(
    string $id,
    string $comment_id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdCommentsGet.
   *
   * List studio comments
   *
   * @param string      $id              (required)
   * @param string      $accept_language (optional, default to 'en')
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdCommentsGet(
    string $id,
    string $accept_language,
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdCommentsPost.
   *
   * Add a comment to a studio
   *
   * @param string                     $id                            (required)
   * @param StudioCommentCreateRequest $studio_comment_create_request (required)
   * @param string                     $accept_language               (optional, default to 'en')
   * @param int                        &$responseCode                 The HTTP Response Code
   * @param array                      $responseHeaders               Additional HTTP headers to return with the response ()
   */
  public function studiosIdCommentsPost(
    string $id,
    StudioCommentCreateRequest $studio_comment_create_request,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdDelete.
   *
   * Delete a studio (only available to studio admins)
   *
   * @param string $id              (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdDelete(
    string $id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdGet.
   *
   * Get studio details (private studios are only available to members)
   *
   * @param string $id              (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdGet(
    string $id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdJoinPost.
   *
   * Join a studio
   *
   * @param string $id              (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdJoinPost(
    string $id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdJoinRequestsGet.
   *
   * List pending join requests for a studio (admin only)
   *
   * @param string      $id              (required)
   * @param string      $accept_language (optional, default to 'en')
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdJoinRequestsGet(
    string $id,
    string $accept_language,
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdJoinRequestsRequestIdAcceptPost.
   *
   * Accept a pending join request (admin only)
   *
   * @param string $id              (required)
   * @param string $request_id      (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdJoinRequestsRequestIdAcceptPost(
    string $id,
    string $request_id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdJoinRequestsRequestIdDeclinePost.
   *
   * Decline a pending join request (admin only)
   *
   * @param string $id              (required)
   * @param string $request_id      (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdJoinRequestsRequestIdDeclinePost(
    string $id,
    string $request_id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdLeaveDelete.
   *
   * Leave a studio
   *
   * @param string $id              (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdLeaveDelete(
    string $id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdMembersGet.
   *
   * List studio members
   *
   * @param string      $id              (required)
   * @param string      $accept_language (optional, default to 'en')
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdMembersGet(
    string $id,
    string $accept_language,
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdMembersUserIdBanPost.
   *
   * Ban a studio member
   *
   * @param string $id              (required)
   * @param string $user_id         (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdMembersUserIdBanPost(
    string $id,
    string $user_id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdMembersUserIdDemotePost.
   *
   * Demote a studio admin to member
   *
   * @param string $id              (required)
   * @param string $user_id         (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdMembersUserIdDemotePost(
    string $id,
    string $user_id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdMembersUserIdPromotePost.
   *
   * Promote a studio member to admin
   *
   * @param string $id              (required)
   * @param string $user_id         (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdMembersUserIdPromotePost(
    string $id,
    string $user_id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdPatch.
   *
   * Update a Studio (only available to studio admins)
   *
   * @param string            $id              (required)
   * @param string            $accept_language (optional, default to 'en')
   * @param string|null       $name            The name of the studio (character: min 3, max 180) (optional)
   * @param string|null       $description     A small description about the Studio (character: min 1, max 3000) (optional)
   * @param bool|null         $is_public       This flag sets the studios&#39; visibility to public or private (optional)
   * @param bool|null         $enable_comments This flag enables or disabled the possibility to add comments to the studio (optional)
   * @param UploadedFile|null $image_file      Cover image; Size limit 1MB; Supported extensions are jpeg, png, webp; (optional)
   * @param int               &$responseCode   The HTTP Response Code
   * @param array             $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdPatch(
    string $id,
    string $accept_language,
    ?string $name,
    ?string $description,
    ?bool $is_public,
    ?bool $enable_comments,
    ?UploadedFile $image_file,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdProjectsGet.
   *
   * List studio projects
   *
   * @param string      $id              (required)
   * @param string      $accept_language (optional, default to 'en')
   * @param int         $limit           (optional, default to 20)
   * @param string|null $cursor          Cursor for pagination (opaque string from the previous response) (optional)
   * @param int         &$responseCode   The HTTP Response Code
   * @param array       $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdProjectsGet(
    string $id,
    string $accept_language,
    int $limit,
    ?string $cursor,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosIdProjectsPost.
   *
   * Add a project to a studio
   *
   * @param string                  $id                         (required)
   * @param StudioAddProjectRequest $studio_add_project_request (required)
   * @param string                  $accept_language            (optional, default to 'en')
   * @param int                     &$responseCode              The HTTP Response Code
   * @param array                   $responseHeaders            Additional HTTP headers to return with the response ()
   */
  public function studiosIdProjectsPost(
    string $id,
    StudioAddProjectRequest $studio_add_project_request,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdProjectsProjectIdDelete.
   *
   * Remove a project from a studio
   *
   * @param string $id              (required)
   * @param string $project_id      (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdProjectsProjectIdDelete(
    string $id,
    string $project_id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): void;

  /**
   * Operation studiosIdUserProjectsGet.
   *
   * List current user's projects with in_studio flag
   *
   * @param string $id              (required)
   * @param string $accept_language (optional, default to 'en')
   * @param int    &$responseCode   The HTTP Response Code
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosIdUserProjectsGet(
    string $id,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;

  /**
   * Operation studiosPost.
   *
   * Create a new Studio
   *
   * @param string            $accept_language (optional, default to 'en')
   * @param string|null       $name            The name of the studio (character: min 3, max 180) (optional)
   * @param string|null       $description     A small description about the Studio (character: min 1, max 3000) (optional)
   * @param bool              $is_public       This flag sets the studios&#39; visibility to public or private (optional, default to true)
   * @param bool              $enable_comments This flag enables or disabled the possibility to add comments to the studio (optional, default to true)
   * @param UploadedFile|null $image_file      Cover image; Size limit 1MB; Supported extensions are jpeg, png, webp; (optional)
   * @param int               &$responseCode   The HTTP Response Code
   * @param array             $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function studiosPost(
    string $accept_language,
    ?string $name,
    ?string $description,
    bool $is_public,
    bool $enable_comments,
    ?UploadedFile $image_file,
    int &$responseCode,
    array &$responseHeaders,
  ): array|object|null;
}
