@web @project_page
Feature: As a visitor I want to see code statistics on the project page

  Scenario: For performance reasons the code statistics are on its own page
    Given there are projects:
      | id | name      |
      | 1  | program 1 |
    And I am on "/app/project/1"
    And I wait for the page to be loaded
    And I click "#projectCodeStatsButton-small"
    And I wait for the page to be loaded
    Then I should be on "/app/project/1/code_statistics"
    And the "#top-app-bar__title" element should contain "Code statistics"

  Scenario: Code statistics provide means to return to the project page
    Given there are projects:
      | id | name      |
      | 1  | program 1 |
    And I am on "/app"
    And I wait for the page to be loaded
    When I go to "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And I click "#top-app-bar__back__btn-back"
    Then I should be on "/app/project/1"

  Scenario: Code statistics page title is no link
    Given there are projects:
      | id | name      |
      | 1  | program 1 |
    And I am on "/app/project/1/code_statistics"
    And I click "#top-app-bar__title"
    Then I should be on "/app/project/1/code_statistics"

  Scenario: On a project page there should be correct stats for all code bricks
    Given I have a project zip "CodeStatistics/code_statistics_compound_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-event-brick" element should not contain "0"
    And the "#number-of-different-event-brick" element should not contain "0"
    And the "#total-number-of-control-brick" element should not contain "0"
    And the "#number-of-different-control-brick" element should not contain "0"
    And the "#total-number-of-motion-brick" element should not contain "0"
    And the "#number-of-different-motion-brick" element should not contain "0"
    But the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "7"
    And the "#number-of-different-control-brick" element should contain "6"
    And the "#total-number-of-motion-brick" element should contain "6"
    And the "#number-of-different-motion-brick" element should contain "3"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats
    Given I have a project zip "CodeStatistics/code_statistics_compound_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    But the "#total-number-of-scenes" element should not contain "0"
    And the "#total-number-of-scripts" element should contain "1"
    But the "#total-number-of-scripts" element should not contain "0"
    And the "#total-number-of-bricks" element should contain "14"
    But the "#total-number-of-bricks" element should not contain "0"
    And the "#total-number-of-objects" element should contain "1"
    But the "#total-number-of-objects" element should not contain "0"
    And the "#total-number-of-looks" element should contain "0"
    But the "#total-number-of-looks" element should not contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    But the "#total-number-of-sounds" element should not contain "3"
    And the "#total-number-of-globals" element should contain "0"
    But the "#total-number-of-globals" element should not contain "3"
    And the "#total-number-of-locals" element should contain "0"
    But the "#total-number-of-locals" element should not contain "7"

  Scenario: On a project page there should be correct stats
    Given I have a project zip "CodeStatistics/code_statistics_mixed_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "2"
    And the "#total-number-of-scripts" element should contain "12"
    And the "#total-number-of-bricks" element should contain "80"
    And the "#total-number-of-objects" element should contain "7"
    And the "#total-number-of-looks" element should contain "10"
    And the "#total-number-of-sounds" element should contain "5"
    And the "#total-number-of-globals" element should contain "2"
    And the "#total-number-of-locals" element should contain "2"
    And the "#total-number-of-event-brick" element should contain "12"
    And the "#number-of-different-event-brick" element should contain "5"
    And the "#total-number-of-control-brick" element should contain "31"
    And the "#number-of-different-control-brick" element should contain "10"
    And the "#total-number-of-motion-brick" element should contain "14"
    And the "#number-of-different-motion-brick" element should contain "7"
    And the "#total-number-of-sound-brick" element should contain "5"
    And the "#number-of-different-sound-brick" element should contain "4"
    And the "#total-number-of-look-brick" element should contain "3"
    And the "#number-of-different-look-brick" element should contain "3"
    And the "#total-number-of-pen-brick" element should contain "3"
    And the "#number-of-different-pen-brick" element should contain "2"
    And the "#total-number-of-data-brick" element should contain "12"
    And the "#number-of-different-data-brick" element should contain "7"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about local and global vars
    Given I have a project zip "CodeStatistics/code_statistics_global_vs_local_variables.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "2"
    And the "#total-number-of-bricks" element should contain "9"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "1"
    And the "#total-number-of-locals" element should contain "4"
    And the "#total-number-of-event-brick" element should contain "2"
    And the "#number-of-different-event-brick" element should contain "2"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "7"
    And the "#number-of-different-data-brick" element should contain "2"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all event bricks
    Given I have a project zip "CodeStatistics/code_statistics_event_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "8"
    And the "#total-number-of-bricks" element should contain "10"
    And the "#total-number-of-objects" element should contain "3"
    And the "#total-number-of-looks" element should contain "2"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "8"
    And the "#number-of-different-event-brick" element should contain "8"
    And the "#total-number-of-control-brick" element should contain "1"
    And the "#number-of-different-control-brick" element should contain "1"
    And the "#total-number-of-motion-brick" element should contain "1"
    And the "#number-of-different-motion-brick" element should contain "1"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all control bricks
    Given I have a project zip "CodeStatistics/code_statistics_control_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "18"
    And the "#total-number-of-objects" element should contain "1"
    And the "#total-number-of-looks" element should contain "0"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "0"
    And the "#number-of-different-event-brick" element should contain "0"
    And the "#total-number-of-control-brick" element should contain "18"
    And the "#number-of-different-control-brick" element should contain "15"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all motion bricks
    Given I have a project zip "CodeStatistics/code_statistics_motion_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "23"
    And the "#total-number-of-objects" element should contain "1"
    And the "#total-number-of-looks" element should contain "0"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "22"
    And the "#number-of-different-motion-brick" element should contain "22"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all sound bricks
    Given I have a project zip "CodeStatistics/code_statistics_sound_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "9"
    And the "#total-number-of-objects" element should contain "1"
    And the "#total-number-of-looks" element should contain "0"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "8"
    And the "#number-of-different-sound-brick" element should contain "8"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all look bricks
    Given I have a project zip "CodeStatistics/code_statistics_look_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "22"
    And the "#total-number-of-objects" element should contain "1"
    And the "#total-number-of-looks" element should contain "0"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "21"
    And the "#number-of-different-look-brick" element should contain "21"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all look bricks
    Given I have a project zip "CodeStatistics/code_statistics_pen_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "7"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "6"
    And the "#number-of-different-pen-brick" element should contain "6"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all data bricks
    Given I have a project zip "CodeStatistics/code_statistics_data_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "15"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "14"
    And the "#number-of-different-data-brick" element should contain "14"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all device bricks
    Given I have a project zip "CodeStatistics/code_statistics_device_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "4"
    And the "#total-number-of-objects" element should contain "1"
    And the "#total-number-of-looks" element should contain "0"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-device-brick" element should contain "3"
    And the "#number-of-different-device-brick" element should contain "3"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all arduino bricks
    Given I have a project zip "CodeStatistics/code_statistics_arduino_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "3"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "2"
    And the "#number-of-different-special-brick" element should contain "2"

  Scenario: On a project page there should be correct stats about all mindstorms ev3 bricks
    Given I have a project zip "CodeStatistics/code_statistics_lego_ev3_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "6"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "5"
    And the "#number-of-different-special-brick" element should contain "5"

  Scenario: On a project page there should be correct stats about all mindstorms nxt bricks
    Given I have a project zip "CodeStatistics/code_statistics_lego_nxt_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "5"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "4"
    And the "#number-of-different-special-brick" element should contain "4"

  Scenario: On a project page there should be correct stats about all embroidery bricks
    Given I have a project zip "CodeStatistics/code_statistics_embroidery_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "2"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "1"
    And the "#number-of-different-special-brick" element should contain "1"

  Scenario: On a project page there should be correct stats about all extended embroidery bricks
    Given I have a project zip "CodeStatistics/code_statistics_embroidery_blocks_extended.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "6"
    And the "#total-number-of-objects" element should contain "1"
    And the "#total-number-of-looks" element should contain "0"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "5"
    And the "#number-of-different-special-brick" element should contain "5"

  Scenario: On a project page there should be correct stats about all ar drone bricks
    Given I have a project zip "CodeStatistics/code_statistics_ar_drone_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "14"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "12"
    And the "#number-of-different-motion-brick" element should contain "12"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "1"
    And the "#number-of-different-look-brick" element should contain "1"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all jumping sumo bricks
    Given I have a project zip "CodeStatistics/code_statistics_jumping_sumo_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "12"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "0"
    And the "#number-of-different-control-brick" element should contain "0"
    And the "#total-number-of-motion-brick" element should contain "11"
    And the "#number-of-different-motion-brick" element should contain "11"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all raspberry pi bricks
    Given I have a project zip "CodeStatistics/code_statistics_raspberrypi_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "6"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "3"
    And the "#number-of-different-control-brick" element should contain "3"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "2"
    And the "#number-of-different-special-brick" element should contain "2"

  Scenario: On a project page there should be correct stats about all nfc bricks
    Given I have a project zip "CodeStatistics/code_statistics_nfc_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "2"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "1"
    And the "#number-of-different-control-brick" element should contain "1"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "0"
    And the "#number-of-different-sound-brick" element should contain "0"
    And the "#total-number-of-look-brick" element should contain "0"
    And the "#number-of-different-look-brick" element should contain "0"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "0"
    And the "#number-of-different-data-brick" element should contain "0"
    And the "#total-number-of-special-brick" element should contain "0"
    And the "#number-of-different-special-brick" element should contain "0"

  Scenario: On a project page there should be correct stats about all phiro bricks
    Given I have a project zip "CodeStatistics/code_statistics_phiro_blocks.catrobat"
    When I upload this generated project with id "1", API version 1
    Given I am on "/app/project/1/code_statistics"
    And I wait for the page to be loaded
    And the "#total-number-of-scenes" element should contain "1"
    And the "#total-number-of-scripts" element should contain "1"
    And the "#total-number-of-bricks" element should contain "15"
    And the "#total-number-of-objects" element should contain "2"
    And the "#total-number-of-looks" element should contain "1"
    And the "#total-number-of-sounds" element should contain "0"
    And the "#total-number-of-globals" element should contain "0"
    And the "#total-number-of-locals" element should contain "0"
    And the "#total-number-of-event-brick" element should contain "1"
    And the "#number-of-different-event-brick" element should contain "1"
    And the "#total-number-of-control-brick" element should contain "3"
    And the "#number-of-different-control-brick" element should contain "3"
    And the "#total-number-of-motion-brick" element should contain "0"
    And the "#number-of-different-motion-brick" element should contain "0"
    And the "#total-number-of-sound-brick" element should contain "1"
    And the "#number-of-different-sound-brick" element should contain "1"
    And the "#total-number-of-look-brick" element should contain "1"
    And the "#number-of-different-look-brick" element should contain "1"
    And the "#total-number-of-pen-brick" element should contain "0"
    And the "#number-of-different-pen-brick" element should contain "0"
    And the "#total-number-of-data-brick" element should contain "6"
    And the "#number-of-different-data-brick" element should contain "1"
    And the "#total-number-of-special-brick" element should contain "3"
    And the "#number-of-different-special-brick" element should contain "3"
