<?php


namespace App\Catrobat\Requests;


use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Class AppRequest
 * @package App\Catrobat\Requests
 *
 * General request, maybe generated by the Catroid/Catty app
 */
class AppRequest
{

  /**
   * @var RequestStack
   */
  protected $request_stack;

  /**
   * AppRequest constructor.
   *
   * @param RequestStack $request_stack
   */
  public function __construct(RequestStack $request_stack)
  {
    $this->request_stack = $request_stack;
  }

  /**
   * @return RequestStack
   */
  public function getRequestStack(): RequestStack
  {
    return $this->request_stack;
  }

  /**
   * @return Request|null
   */
  public function getCurrentRequest()
  {
    return $this->request_stack->getCurrentRequest();
  }

  /**
   * Checks if "BuildType/debug" is defined in the User-Agent string.
   * @return bool
   */
  public function isDebugBuildRequest(): bool
  {
    $request = $this->request_stack->getCurrentRequest();
    if ($request === null)
    {
      return false;
    }

    $user_agent = $request->headers->get('User-Agent');
    if ($user_agent === null)
    {
      return false;
    }
    if (is_array($user_agent))
    {
      if (count($user_agent) > 0)
      {
        $user_agent = $user_agent[0];
      }
      else
      {
        return false;
      }
    }

    return strpos(strtolower($user_agent), " buildtype/debug") !== false;
  }


  /**
   * Checks if "theme/*" is defined in the User-Agent string.
   *
   * @return String
   */
  public function getThemeDefinedInRequest(): String
  {
    $request = $this->request_stack->getCurrentRequest();
    if ($request === null)
    {
      return "";
    }

    $user_agent = $request->headers->get('User-Agent');
    if ($user_agent === null)
    {
      return "";
    }
    if (is_array($user_agent))
    {
      if (count($user_agent) > 0)
      {
        $user_agent = $user_agent[0];
      }
      else
      {
        return "";
      }
    }

    $user_agent_attributes = explode(" ", strtolower($user_agent));

    foreach ($user_agent_attributes as $attribute)
    {
      if (strpos($attribute, 'theme/') !== false)
      {
        return str_replace('theme/', '', $attribute);
      }
    }

    return "";
  }

}