# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ** Check for new bricks **
#
#   This check (only) compares the Catroweb brick support with all existing Catroid bricks.
#   Bricks implemented by Catty are not checked, since the Android team usually is way faster than the iOS team.
#
#   - Why do we need those bricks?
#
#       We need the information about those bricks to present users valid code statisitics and code views.
#       Automating the checks, provides Catroweb developers with immediate feedback about new bricks and how to
#       integrate them into the project, even if the team overlapping communication is missing.
#
name: Check for new bricks

#
# This check is independent of a pull request, hence, it is executed once a day on a schedule.
# In case, an additional run is required, a manual dispatch trigger is also enabled.
#
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  #
  # The `check-bricks` script is written in Php, hence, we have to ensure Php is installed.
  # However, it would be possible to write the script in any language.
  # Next it is essential to ensure that the script is executable.
  # Finally, all that is left to do, is to run the script to compare the bricks.
  # For more information about the brick comparison, check out the script.
  #
  check_for_new_catroid_bricks:
    # Only should run on the main repo. There is no need to run the same check on multiple repositories.
    if: github.repository == 'Catrobat/Catroweb'

    name: Check for new Catroid Bricks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set Permissions
        run: sudo chmod 755 bin/checkCatroidRepositoryForNewBricks

      - name: Check Catroid Repository for new bricks
        run: bin/checkCatroidRepositoryForNewBricks
