
# Runs all Behat test suites parallel using the matrix strategy via docker in the latest ubuntu build.

name: Behat Tests

on: [push, pull_request] # ToDo for next version: trigger manually


jobs:

  tests_behat:
    name: Behat Tests
    runs-on: ubuntu-latest
    strategy:
      #
      #  Notes:
      #         - Check the behat.yml when changing / creating new suites
      #         - suites will finish their work even if another suite fails (fail-fast: false)
      #
      fail-fast: false
      matrix:
        testSuite: ['admin', 'api', 'ci', 'flavor', 'web', 'gamejam', 'gamejam_web', 'gamejam_javascript']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd docker
          docker-compose -f docker-compose.test.yml build
          docker-compose -f docker-compose.test.yml up -d

      - name: Behat ${{ matrix.testSuite }} tests
        run:
          docker exec app.catroweb.test bin/behat -s ${{ matrix.testSuite }}

      # Behat tests often have timing issues when not written in a save way
      - name: Rerun failed Behat ${{ matrix.testSuite }} tests
        if: failure()
        run:
          docker exec app.catroweb.test bin/behat -s ${{ matrix.testSuite }} --rerun

      - name: Rerun failed Behat ${{ matrix.testSuite }} tests
        if: failure()
        run:
          docker exec app.catroweb.test bin/behat -s ${{ matrix.testSuite }} --rerun

      - name: Rerun failed Behat ${{ matrix.testSuite }} tests
        if: failure()
        run:
          docker exec app.catroweb.test bin/behat -s ${{ matrix.testSuite }} --rerun

      - name: Rerun failed Behat ${{ matrix.testSuite }} tests
        if: failure()
        run:
          docker exec app.catroweb.test bin/behat -s ${{ matrix.testSuite }} --rerun